local M = {}

M.language_options = {
    "auto", "zh-TW", "en", "zh-CN", "ja", "ko", "fr", "de", "it",
    "es-ES", "es-419", "pt-BR", "ru", "id", "th", "tr", "vi", "pl",
}

M.native_names = {
    ["en"] = "English",
    ["zh-CN"] = "简体中文",
    ["zh-TW"] = "繁體中文",
    ["ja"] = "日本語",
    ["fr"] = "Français",
    ["it"] = "Italiano",
    ["de"] = "Deutsch",
    ["es-ES"] = "Español (España)",
    ["pt-BR"] = "Português (Brasil)",
    ["ru"] = "Русский",
    ["ko"] = "한국어",
    ["id"] = "Bahasa Indonesia",
    ["es-419"] = "Español (Latinoamérica)",
    ["th"] = "ไทย",
    ["tr"] = "Türkçe",
    ["vi"] = "Tiếng Việt",
    ["pl"] = "Polski",
}

M.strings = {
    ["en"] = {
        hud_settings_title = "PAL SKILL DPS | SETTINGS",
        hud_settings_note = "Settings save automatically. Player damage applies from the next hit.",
        hud_settings_footer = "UP/DOWN select  LEFT/RIGHT/ENTER change  {key} close",
        hud_setting_language = "Display language",
        hud_setting_show = "Show skill DPS panel",
        hud_setting_player = "Include player/weapon damage",
        hud_setting_detail = "Detail mode",
        hud_setting_internal = "Show internal skill code",
        hud_setting_anchor = "Panel position",
        hud_setting_scale = "Panel scale",
        hud_setting_keep = "Keep final result",
        hud_setting_chat = "Chat output",
        hud_setting_reset = "Reset current test",
        hud_value_on = "ON",
        hud_value_off = "OFF",
        hud_value_compact = "COMPACT",
        hud_value_full = "FULL",
        hud_value_top_left = "TOP LEFT",
        hud_value_top_right = "TOP RIGHT",
        hud_value_summary = "SUMMARY",
        hud_value_press_enter = "PRESS ENTER",
        hud_value_follow_game = "Follow game",
        hud_title = "PAL SKILL DPS | DAMAGE LAB",
        hud_state_finished = "FINISHED",
        hud_state_live = "LIVE",
        hud_summary = "{state} | {boss} | {seconds}s | damage {damage} | encounter DPS {dps}",
        hud_source = "[{source}] damage {damage} | DPS {dps} | hits {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dmg | {dps} DPS | {casts} casts",
        hud_skill_primary = "  {rank}. {skill} | damage {damage} | encounter DPS {dps} | hits {hits} | casts {casts}",
        hud_skill_timing = "     damage/cast {per_cast} | action {action}s | cast DPS {cast_dps} | timing {complete}/{casts}",
        hud_skill_cooldown = "     panel CD {panel}s | actual interval {interval}s | AI/reuse gap {gap}s",
        hud_waiting = "Waiting for a Pal skill to hit the boss...",
        hud_footer = "{key} settings | player damage {player} | chat {chat}",
    },
    ["zh-TW"] = {
        hud_settings_title = "帕魯技能 DPS｜設定",
        hud_settings_note = "設定會自動儲存；人物傷害切換從下一次命中開始生效。",
        hud_settings_footer = "↑↓ 選擇　←→／Enter 調整　{key} 關閉",
        hud_setting_language = "顯示語言",
        hud_setting_show = "顯示技能 DPS 面板",
        hud_setting_player = "納入人物／武器傷害",
        hud_setting_detail = "資料密度",
        hud_setting_internal = "顯示內部英文代碼",
        hud_setting_anchor = "面板位置",
        hud_setting_scale = "面板縮放",
        hud_setting_keep = "戰後保留結果",
        hud_setting_chat = "聊天輸出",
        hud_setting_reset = "清除本場測試",
        hud_value_on = "開",
        hud_value_off = "關",
        hud_value_compact = "精簡",
        hud_value_full = "完整",
        hud_value_top_left = "左上",
        hud_value_top_right = "右上",
        hud_value_summary = "摘要",
        hud_value_press_enter = "按 Enter",
        hud_value_follow_game = "跟隨遊戲",
        hud_title = "帕魯技能 DPS｜傷害驗證",
        hud_state_finished = "完成",
        hud_state_live = "記錄中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜總傷害 {damage}｜整場 DPS {dps}",
        hud_source = "【{source}】傷害 {damage}｜DPS {dps}｜命中 {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} 傷害｜{dps} DPS｜{casts}次",
        hud_skill_primary = "  {rank}. {skill}｜傷害 {damage}｜整場DPS {dps}｜命中 {hits}｜施放 {casts}",
        hud_skill_timing = "     每次 {per_cast}｜動作 {action}秒｜施放DPS {cast_dps}｜完整計時 {complete}/{casts}",
        hud_skill_cooldown = "     面板CD {panel}秒｜實際間隔 {interval}秒｜AI／再用空窗 {gap}秒",
        hud_waiting = "等待帕魯技能命中 Boss…",
        hud_footer = "{key} 設定｜人物傷害 {player}｜聊天 {chat}",
    },
    ["zh-CN"] = {
        hud_settings_title = "帕鲁技能 DPS｜设置",
        hud_settings_note = "设置会自动保存；人物伤害切换从下一次命中开始生效。",
        hud_settings_footer = "↑↓ 选择　←→／Enter 调整　{key} 关闭",
        hud_setting_language = "显示语言",
        hud_setting_show = "显示技能 DPS 面板",
        hud_setting_player = "纳入人物／武器伤害",
        hud_setting_detail = "数据密度",
        hud_setting_internal = "显示内部英文代码",
        hud_setting_anchor = "面板位置",
        hud_setting_scale = "面板缩放",
        hud_setting_keep = "战后保留结果",
        hud_setting_chat = "聊天输出",
        hud_setting_reset = "清除本场测试",
        hud_value_on = "开",
        hud_value_off = "关",
        hud_value_compact = "精简",
        hud_value_full = "完整",
        hud_value_top_left = "左上",
        hud_value_top_right = "右上",
        hud_value_summary = "摘要",
        hud_value_press_enter = "按 Enter",
        hud_value_follow_game = "跟随游戏",
        hud_title = "帕鲁技能 DPS｜伤害验证",
        hud_state_finished = "完成",
        hud_state_live = "记录中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜总伤害 {damage}｜整场 DPS {dps}",
        hud_source = "【{source}】伤害 {damage}｜DPS {dps}｜命中 {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} 伤害｜{dps} DPS｜{casts}次",
        hud_skill_primary = "  {rank}. {skill}｜伤害 {damage}｜整场DPS {dps}｜命中 {hits}｜施放 {casts}",
        hud_skill_timing = "     每次 {per_cast}｜动作 {action}秒｜施放DPS {cast_dps}｜完整计时 {complete}/{casts}",
        hud_skill_cooldown = "     面板CD {panel}秒｜实际间隔 {interval}秒｜AI／再用空窗 {gap}秒",
        hud_waiting = "等待帕鲁技能命中 Boss…",
        hud_footer = "{key} 设置｜人物伤害 {player}｜聊天 {chat}",
    },
    ["ja"] = {
        hud_settings_title = "パルスキル DPS｜設定",
        hud_settings_note = "設定は自動保存されます。プレイヤーダメージは次のヒットから反映されます。",
        hud_settings_footer = "↑↓ 選択　←→／Enter 変更　{key} 閉じる",
        hud_setting_language = "表示言語",
        hud_setting_show = "スキル DPS パネルを表示",
        hud_setting_player = "プレイヤー／武器ダメージを含める",
        hud_setting_detail = "表示密度",
        hud_setting_internal = "内部スキルコードを表示",
        hud_setting_anchor = "パネル位置",
        hud_setting_scale = "パネル倍率",
        hud_setting_keep = "戦闘後も結果を表示",
        hud_setting_chat = "チャット出力",
        hud_setting_reset = "現在のテストをリセット",
        hud_value_on = "オン", hud_value_off = "オフ",
        hud_value_compact = "簡易", hud_value_full = "詳細",
        hud_value_top_left = "左上", hud_value_top_right = "右上",
        hud_value_summary = "概要", hud_value_press_enter = "Enter を押す",
        hud_value_follow_game = "ゲームに合わせる",
        hud_title = "パルスキル DPS｜ダメージ検証",
        hud_state_finished = "完了", hud_state_live = "計測中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜ダメージ {damage}｜戦闘 DPS {dps}",
        hud_source = "【{source}】ダメージ {damage}｜DPS {dps}｜ヒット {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} ダメージ｜{dps} DPS｜{casts}回",
        hud_skill_primary = "  {rank}. {skill}｜ダメージ {damage}｜戦闘DPS {dps}｜ヒット {hits}｜発動 {casts}",
        hud_skill_timing = "     1回 {per_cast}｜動作 {action}秒｜発動DPS {cast_dps}｜完全計測 {complete}/{casts}",
        hud_skill_cooldown = "     表示CD {panel}秒｜実間隔 {interval}秒｜AI／再使用待ち {gap}秒",
        hud_waiting = "パルのスキルがボスに当たるのを待っています…",
        hud_footer = "{key} 設定｜プレイヤーダメージ {player}｜チャット {chat}",
    },
    ["ko"] = {
        hud_settings_title = "팰 스킬 DPS | 설정",
        hud_settings_note = "설정은 자동 저장됩니다. 플레이어 피해는 다음 타격부터 적용됩니다.",
        hud_settings_footer = "↑↓ 선택  ←→/Enter 변경  {key} 닫기",
        hud_setting_language = "표시 언어", hud_setting_show = "스킬 DPS 패널 표시",
        hud_setting_player = "플레이어/무기 피해 포함", hud_setting_detail = "표시 밀도",
        hud_setting_internal = "내부 스킬 코드 표시", hud_setting_anchor = "패널 위치",
        hud_setting_scale = "패널 크기", hud_setting_keep = "전투 후 결과 유지",
        hud_setting_chat = "채팅 출력", hud_setting_reset = "현재 테스트 초기화",
        hud_value_on = "켜기", hud_value_off = "끄기", hud_value_compact = "간단",
        hud_value_full = "전체", hud_value_top_left = "왼쪽 위", hud_value_top_right = "오른쪽 위",
        hud_value_summary = "요약", hud_value_press_enter = "Enter 누르기", hud_value_follow_game = "게임 언어 따르기",
        hud_title = "팰 스킬 DPS | 피해 검증", hud_state_finished = "완료", hud_state_live = "기록 중",
        hud_summary = "{state} | {boss} | {seconds}초 | 총 피해 {damage} | 전투 DPS {dps}",
        hud_source = "[{source}] 피해 {damage} | DPS {dps} | 적중 {hits}",
        hud_skill_compact = "  {rank}. {skill} | 피해 {damage} | DPS {dps} | {casts}회",
        hud_skill_primary = "  {rank}. {skill} | 피해 {damage} | 전투DPS {dps} | 적중 {hits} | 사용 {casts}",
        hud_skill_timing = "     회당 {per_cast} | 동작 {action}초 | 사용DPS {cast_dps} | 완전 측정 {complete}/{casts}",
        hud_skill_cooldown = "     표시CD {panel}초 | 실제 간격 {interval}초 | AI/재사용 공백 {gap}초",
        hud_waiting = "팰 스킬이 보스에게 적중하기를 기다리는 중…",
        hud_footer = "{key} 설정 | 플레이어 피해 {player} | 채팅 {chat}",
    },
    ["fr"] = {
        hud_settings_title = "DPS DES COMPÉTENCES | RÉGLAGES",
        hud_settings_note = "Les réglages sont enregistrés automatiquement. Les dégâts du joueur s'appliquent au prochain coup.",
        hud_settings_footer = "↑↓ sélectionner  ←→/Entrée modifier  {key} fermer",
        hud_setting_language = "Langue d'affichage", hud_setting_show = "Afficher le panneau DPS",
        hud_setting_player = "Inclure dégâts joueur/arme", hud_setting_detail = "Niveau de détail",
        hud_setting_internal = "Afficher le code interne", hud_setting_anchor = "Position du panneau",
        hud_setting_scale = "Échelle du panneau", hud_setting_keep = "Conserver le résultat final",
        hud_setting_chat = "Sortie du chat", hud_setting_reset = "Réinitialiser le test",
        hud_value_on = "OUI", hud_value_off = "NON", hud_value_compact = "COMPACT",
        hud_value_full = "COMPLET", hud_value_top_left = "EN HAUT À GAUCHE", hud_value_top_right = "EN HAUT À DROITE",
        hud_value_summary = "RÉSUMÉ", hud_value_press_enter = "APPUYER SUR ENTRÉE", hud_value_follow_game = "Suivre le jeu",
        hud_title = "DPS DES COMPÉTENCES | LABO DE DÉGÂTS", hud_state_finished = "TERMINÉ", hud_state_live = "EN COURS",
        hud_summary = "{state} | {boss} | {seconds}s | dégâts {damage} | DPS du combat {dps}",
        hud_source = "[{source}] dégâts {damage} | DPS {dps} | coups {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dégâts | {dps} DPS | {casts} utilisations",
        hud_skill_primary = "  {rank}. {skill} | dégâts {damage} | DPS combat {dps} | coups {hits} | utilisations {casts}",
        hud_skill_timing = "     dégâts/util. {per_cast} | action {action}s | DPS util. {cast_dps} | suivi {complete}/{casts}",
        hud_skill_cooldown = "     CD affiché {panel}s | intervalle réel {interval}s | attente IA/réutil. {gap}s",
        hud_waiting = "En attente d'une compétence de Pal touchant le boss…",
        hud_footer = "{key} réglages | dégâts joueur {player} | chat {chat}",
    },
    ["de"] = {
        hud_settings_title = "PAL-FÄHIGKEITS-DPS | EINSTELLUNGEN",
        hud_settings_note = "Einstellungen werden automatisch gespeichert. Spielerschaden gilt ab dem nächsten Treffer.",
        hud_settings_footer = "↑↓ wählen  ←→/Enter ändern  {key} schließen",
        hud_setting_language = "Anzeigesprache", hud_setting_show = "Fähigkeits-DPS anzeigen",
        hud_setting_player = "Spieler-/Waffenschaden einbeziehen", hud_setting_detail = "Detailgrad",
        hud_setting_internal = "Internen Fähigkeitencode anzeigen", hud_setting_anchor = "Panelposition",
        hud_setting_scale = "Panelgröße", hud_setting_keep = "Endergebnis behalten",
        hud_setting_chat = "Chat-Ausgabe", hud_setting_reset = "Aktuellen Test zurücksetzen",
        hud_value_on = "AN", hud_value_off = "AUS", hud_value_compact = "KOMPAKT",
        hud_value_full = "VOLL", hud_value_top_left = "OBEN LINKS", hud_value_top_right = "OBEN RECHTS",
        hud_value_summary = "ZUSAMMENFASSUNG", hud_value_press_enter = "ENTER DRÜCKEN", hud_value_follow_game = "Spiel folgen",
        hud_title = "PAL-FÄHIGKEITS-DPS | SCHADENSLABOR", hud_state_finished = "BEENDET", hud_state_live = "AKTIV",
        hud_summary = "{state} | {boss} | {seconds}s | Schaden {damage} | Kampf-DPS {dps}",
        hud_source = "[{source}] Schaden {damage} | DPS {dps} | Treffer {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} Schaden | {dps} DPS | {casts} Einsätze",
        hud_skill_primary = "  {rank}. {skill} | Schaden {damage} | Kampf-DPS {dps} | Treffer {hits} | Einsätze {casts}",
        hud_skill_timing = "     Schaden/Einsatz {per_cast} | Aktion {action}s | Einsatz-DPS {cast_dps} | Messung {complete}/{casts}",
        hud_skill_cooldown = "     Panel-CD {panel}s | reales Intervall {interval}s | KI/Wiederverwendung {gap}s",
        hud_waiting = "Warte auf einen Pal-Fähigkeitstreffer am Boss…",
        hud_footer = "{key} Einstellungen | Spielerschaden {player} | Chat {chat}",
    },
    ["it"] = {
        hud_settings_title = "DPS ABILITÀ PAL | IMPOSTAZIONI",
        hud_settings_note = "Le impostazioni vengono salvate automaticamente. I danni del giocatore valgono dal prossimo colpo.",
        hud_settings_footer = "↑↓ seleziona  ←→/Invio modifica  {key} chiudi",
        hud_setting_language = "Lingua", hud_setting_show = "Mostra pannello DPS abilità",
        hud_setting_player = "Includi danni giocatore/arma", hud_setting_detail = "Livello di dettaglio",
        hud_setting_internal = "Mostra codice abilità interno", hud_setting_anchor = "Posizione pannello",
        hud_setting_scale = "Scala pannello", hud_setting_keep = "Mantieni risultato finale",
        hud_setting_chat = "Output chat", hud_setting_reset = "Azzera test corrente",
        hud_value_on = "SÌ", hud_value_off = "NO", hud_value_compact = "COMPATTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "IN ALTO A SINISTRA", hud_value_top_right = "IN ALTO A DESTRA",
        hud_value_summary = "RIEPILOGO", hud_value_press_enter = "PREMI INVIO", hud_value_follow_game = "Segui il gioco",
        hud_title = "DPS ABILITÀ PAL | LABORATORIO DANNI", hud_state_finished = "FINITO", hud_state_live = "ATTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | danni {damage} | DPS scontro {dps}",
        hud_source = "[{source}] danni {damage} | DPS {dps} | colpi {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} danni | {dps} DPS | {casts} usi",
        hud_skill_primary = "  {rank}. {skill} | danni {damage} | DPS scontro {dps} | colpi {hits} | usi {casts}",
        hud_skill_timing = "     danni/uso {per_cast} | azione {action}s | DPS uso {cast_dps} | misure {complete}/{casts}",
        hud_skill_cooldown = "     CD pannello {panel}s | intervallo reale {interval}s | attesa IA/riuso {gap}s",
        hud_waiting = "In attesa che un'abilità Pal colpisca il boss…",
        hud_footer = "{key} impostazioni | danni giocatore {player} | chat {chat}",
    },
    ["es-ES"] = {
        hud_settings_title = "DPS DE HABILIDADES | AJUSTES",
        hud_settings_note = "Los ajustes se guardan automáticamente. El daño del jugador se aplica desde el siguiente golpe.",
        hud_settings_footer = "↑↓ seleccionar  ←→/Intro cambiar  {key} cerrar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar panel DPS de habilidades",
        hud_setting_player = "Incluir daño de jugador/arma", hud_setting_detail = "Nivel de detalle",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posición del panel",
        hud_setting_scale = "Escala del panel", hud_setting_keep = "Conservar resultado final",
        hud_setting_chat = "Salida del chat", hud_setting_reset = "Reiniciar prueba actual",
        hud_value_on = "SÍ", hud_value_off = "NO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "ARRIBA IZQUIERDA", hud_value_top_right = "ARRIBA DERECHA",
        hud_value_summary = "RESUMEN", hud_value_press_enter = "PULSA INTRO", hud_value_follow_game = "Seguir el juego",
        hud_title = "DPS DE HABILIDADES | LABORATORIO DE DAÑO", hud_state_finished = "TERMINADO", hud_state_live = "ACTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | daño {damage} | DPS del combate {dps}",
        hud_source = "[{source}] daño {damage} | DPS {dps} | impactos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} daño | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | daño {damage} | DPS combate {dps} | impactos {hits} | usos {casts}",
        hud_skill_timing = "     daño/uso {per_cast} | acción {action}s | DPS uso {cast_dps} | medición {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Esperando que una habilidad de Pal golpee al jefe…",
        hud_footer = "{key} ajustes | daño jugador {player} | chat {chat}",
    },
    ["es-419"] = {
        hud_settings_title = "DPS DE HABILIDADES | AJUSTES",
        hud_settings_note = "Los ajustes se guardan automáticamente. El daño del jugador aplica desde el siguiente golpe.",
        hud_settings_footer = "↑↓ seleccionar  ←→/Enter cambiar  {key} cerrar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar panel DPS de habilidades",
        hud_setting_player = "Incluir daño de jugador/arma", hud_setting_detail = "Nivel de detalle",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posición del panel",
        hud_setting_scale = "Escala del panel", hud_setting_keep = "Conservar resultado final",
        hud_setting_chat = "Salida del chat", hud_setting_reset = "Reiniciar prueba actual",
        hud_value_on = "SÍ", hud_value_off = "NO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "ARRIBA IZQUIERDA", hud_value_top_right = "ARRIBA DERECHA",
        hud_value_summary = "RESUMEN", hud_value_press_enter = "PRESIONA ENTER", hud_value_follow_game = "Seguir el juego",
        hud_title = "DPS DE HABILIDADES | LABORATORIO DE DAÑO", hud_state_finished = "TERMINADO", hud_state_live = "ACTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | daño {damage} | DPS del combate {dps}",
        hud_source = "[{source}] daño {damage} | DPS {dps} | impactos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} daño | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | daño {damage} | DPS combate {dps} | impactos {hits} | usos {casts}",
        hud_skill_timing = "     daño/uso {per_cast} | acción {action}s | DPS uso {cast_dps} | medición {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Esperando que una habilidad de Pal golpee al jefe…",
        hud_footer = "{key} ajustes | daño jugador {player} | chat {chat}",
    },
    ["pt-BR"] = {
        hud_settings_title = "DPS DE HABILIDADES | CONFIGURAÇÕES",
        hud_settings_note = "As configurações são salvas automaticamente. O dano do jogador vale a partir do próximo acerto.",
        hud_settings_footer = "↑↓ selecionar  ←→/Enter alterar  {key} fechar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar painel de DPS",
        hud_setting_player = "Incluir dano de jogador/arma", hud_setting_detail = "Nível de detalhes",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posição do painel",
        hud_setting_scale = "Escala do painel", hud_setting_keep = "Manter resultado final",
        hud_setting_chat = "Saída no chat", hud_setting_reset = "Reiniciar teste atual",
        hud_value_on = "LIGADO", hud_value_off = "DESLIGADO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "SUPERIOR ESQUERDO", hud_value_top_right = "SUPERIOR DIREITO",
        hud_value_summary = "RESUMO", hud_value_press_enter = "PRESSIONE ENTER", hud_value_follow_game = "Seguir o jogo",
        hud_title = "DPS DE HABILIDADES | LABORATÓRIO DE DANO", hud_state_finished = "CONCLUÍDO", hud_state_live = "ATIVO",
        hud_summary = "{state} | {boss} | {seconds}s | dano {damage} | DPS do combate {dps}",
        hud_source = "[{source}] dano {damage} | DPS {dps} | acertos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dano | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | dano {damage} | DPS combate {dps} | acertos {hits} | usos {casts}",
        hud_skill_timing = "     dano/uso {per_cast} | ação {action}s | DPS uso {cast_dps} | medição {complete}/{casts}",
        hud_skill_cooldown = "     CD painel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Aguardando uma habilidade de Pal atingir o chefe…",
        hud_footer = "{key} configurações | dano jogador {player} | chat {chat}",
    },
    ["ru"] = {
        hud_settings_title = "DPS НАВЫКОВ ПАЛА | НАСТРОЙКИ",
        hud_settings_note = "Настройки сохраняются автоматически. Урон игрока учитывается со следующего попадания.",
        hud_settings_footer = "↑↓ выбор  ←→/Enter изменить  {key} закрыть",
        hud_setting_language = "Язык", hud_setting_show = "Показывать панель DPS",
        hud_setting_player = "Учитывать урон игрока/оружия", hud_setting_detail = "Подробность",
        hud_setting_internal = "Показывать внутренний код", hud_setting_anchor = "Положение панели",
        hud_setting_scale = "Масштаб панели", hud_setting_keep = "Сохранить итог",
        hud_setting_chat = "Вывод в чат", hud_setting_reset = "Сбросить текущий тест",
        hud_value_on = "ВКЛ", hud_value_off = "ВЫКЛ", hud_value_compact = "КРАТКО",
        hud_value_full = "ПОЛНО", hud_value_top_left = "СВЕРХУ СЛЕВА", hud_value_top_right = "СВЕРХУ СПРАВА",
        hud_value_summary = "СВОДКА", hud_value_press_enter = "НАЖМИТЕ ENTER", hud_value_follow_game = "Как в игре",
        hud_title = "DPS НАВЫКОВ ПАЛА | ПРОВЕРКА УРОНА", hud_state_finished = "ЗАВЕРШЕНО", hud_state_live = "ЗАПИСЬ",
        hud_summary = "{state} | {boss} | {seconds}с | урон {damage} | DPS боя {dps}",
        hud_source = "[{source}] урон {damage} | DPS {dps} | попадания {hits}",
        hud_skill_compact = "  {rank}. {skill} | урон {damage} | DPS {dps} | применений {casts}",
        hud_skill_primary = "  {rank}. {skill} | урон {damage} | DPS боя {dps} | попаданий {hits} | применений {casts}",
        hud_skill_timing = "     урон/прим. {per_cast} | действие {action}с | DPS прим. {cast_dps} | замер {complete}/{casts}",
        hud_skill_cooldown = "     CD панели {panel}с | реальный интервал {interval}с | ожидание ИИ/повтора {gap}с",
        hud_waiting = "Ожидание попадания навыком Пала по боссу…",
        hud_footer = "{key} настройки | урон игрока {player} | чат {chat}",
    },
    ["id"] = {
        hud_settings_title = "DPS SKILL PAL | PENGATURAN",
        hud_settings_note = "Pengaturan disimpan otomatis. Damage pemain berlaku mulai hit berikutnya.",
        hud_settings_footer = "↑↓ pilih  ←→/Enter ubah  {key} tutup",
        hud_setting_language = "Bahasa tampilan", hud_setting_show = "Tampilkan panel DPS skill",
        hud_setting_player = "Sertakan damage pemain/senjata", hud_setting_detail = "Tingkat detail",
        hud_setting_internal = "Tampilkan kode skill internal", hud_setting_anchor = "Posisi panel",
        hud_setting_scale = "Skala panel", hud_setting_keep = "Simpan hasil akhir",
        hud_setting_chat = "Output chat", hud_setting_reset = "Reset tes saat ini",
        hud_value_on = "NYALA", hud_value_off = "MATI", hud_value_compact = "RINGKAS",
        hud_value_full = "LENGKAP", hud_value_top_left = "KIRI ATAS", hud_value_top_right = "KANAN ATAS",
        hud_value_summary = "RINGKASAN", hud_value_press_enter = "TEKAN ENTER", hud_value_follow_game = "Ikuti game",
        hud_title = "DPS SKILL PAL | LAB DAMAGE", hud_state_finished = "SELESAI", hud_state_live = "MEREKAM",
        hud_summary = "{state} | {boss} | {seconds}dtk | damage {damage} | DPS pertempuran {dps}",
        hud_source = "[{source}] damage {damage} | DPS {dps} | hit {hits}",
        hud_skill_compact = "  {rank}. {skill} | damage {damage} | DPS {dps} | {casts} pemakaian",
        hud_skill_primary = "  {rank}. {skill} | damage {damage} | DPS pertempuran {dps} | hit {hits} | pemakaian {casts}",
        hud_skill_timing = "     damage/pakai {per_cast} | aksi {action}dtk | DPS pakai {cast_dps} | pengukuran {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}dtk | interval nyata {interval}dtk | jeda AI/pakai ulang {gap}dtk",
        hud_waiting = "Menunggu skill Pal mengenai bos…",
        hud_footer = "{key} pengaturan | damage pemain {player} | chat {chat}",
    },
    ["th"] = {
        hud_settings_title = "DPS สกิลพัล | ตั้งค่า",
        hud_settings_note = "บันทึกการตั้งค่าอัตโนมัติ ดาเมจผู้เล่นมีผลตั้งแต่การโจมตีครั้งถัดไป",
        hud_settings_footer = "↑↓ เลือก  ←→/Enter เปลี่ยน  {key} ปิด",
        hud_setting_language = "ภาษา", hud_setting_show = "แสดงแผง DPS สกิล",
        hud_setting_player = "รวมดาเมจผู้เล่น/อาวุธ", hud_setting_detail = "ระดับรายละเอียด",
        hud_setting_internal = "แสดงรหัสสกิลภายใน", hud_setting_anchor = "ตำแหน่งแผง",
        hud_setting_scale = "ขนาดแผง", hud_setting_keep = "เก็บผลลัพธ์หลังจบ",
        hud_setting_chat = "ข้อความแชต", hud_setting_reset = "รีเซ็ตการทดสอบนี้",
        hud_value_on = "เปิด", hud_value_off = "ปิด", hud_value_compact = "ย่อ",
        hud_value_full = "เต็ม", hud_value_top_left = "ซ้ายบน", hud_value_top_right = "ขวาบน",
        hud_value_summary = "สรุป", hud_value_press_enter = "กด Enter", hud_value_follow_game = "ตามภาษาเกม",
        hud_title = "DPS สกิลพัล | ทดสอบดาเมจ", hud_state_finished = "เสร็จสิ้น", hud_state_live = "กำลังบันทึก",
        hud_summary = "{state} | {boss} | {seconds}วิ | ดาเมจ {damage} | DPS การต่อสู้ {dps}",
        hud_source = "[{source}] ดาเมจ {damage} | DPS {dps} | โดน {hits}",
        hud_skill_compact = "  {rank}. {skill} | ดาเมจ {damage} | DPS {dps} | ใช้ {casts} ครั้ง",
        hud_skill_primary = "  {rank}. {skill} | ดาเมจ {damage} | DPS การต่อสู้ {dps} | โดน {hits} | ใช้ {casts}",
        hud_skill_timing = "     ดาเมจ/ครั้ง {per_cast} | แอ็กชัน {action}วิ | DPS ต่อครั้ง {cast_dps} | จับเวลา {complete}/{casts}",
        hud_skill_cooldown = "     CD แผง {panel}วิ | ช่วงจริง {interval}วิ | ช่องว่าง AI/ใช้ซ้ำ {gap}วิ",
        hud_waiting = "กำลังรอสกิลพัลโจมตีบอส…",
        hud_footer = "{key} ตั้งค่า | ดาเมจผู้เล่น {player} | แชต {chat}",
    },
    ["tr"] = {
        hud_settings_title = "PAL YETENEK DPS | AYARLAR",
        hud_settings_note = "Ayarlar otomatik kaydedilir. Oyuncu hasarı bir sonraki vuruştan itibaren uygulanır.",
        hud_settings_footer = "↑↓ seç  ←→/Enter değiştir  {key} kapat",
        hud_setting_language = "Görüntü dili", hud_setting_show = "Yetenek DPS panelini göster",
        hud_setting_player = "Oyuncu/silah hasarını dahil et", hud_setting_detail = "Ayrıntı düzeyi",
        hud_setting_internal = "Dahili yetenek kodunu göster", hud_setting_anchor = "Panel konumu",
        hud_setting_scale = "Panel ölçeği", hud_setting_keep = "Sonucu savaş sonrası tut",
        hud_setting_chat = "Sohbet çıktısı", hud_setting_reset = "Mevcut testi sıfırla",
        hud_value_on = "AÇIK", hud_value_off = "KAPALI", hud_value_compact = "KISA",
        hud_value_full = "TAM", hud_value_top_left = "SOL ÜST", hud_value_top_right = "SAĞ ÜST",
        hud_value_summary = "ÖZET", hud_value_press_enter = "ENTER'A BAS", hud_value_follow_game = "Oyunu takip et",
        hud_title = "PAL YETENEK DPS | HASAR LABORATUVARI", hud_state_finished = "BİTTİ", hud_state_live = "KAYITTA",
        hud_summary = "{state} | {boss} | {seconds}sn | hasar {damage} | savaş DPS {dps}",
        hud_source = "[{source}] hasar {damage} | DPS {dps} | isabet {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} hasar | {dps} DPS | {casts} kullanım",
        hud_skill_primary = "  {rank}. {skill} | hasar {damage} | savaş DPS {dps} | isabet {hits} | kullanım {casts}",
        hud_skill_timing = "     hasar/kullanım {per_cast} | eylem {action}sn | kullanım DPS {cast_dps} | ölçüm {complete}/{casts}",
        hud_skill_cooldown = "     panel CD {panel}sn | gerçek aralık {interval}sn | AI/yeniden kullanım {gap}sn",
        hud_waiting = "Bir Pal yeteneğinin bossa vurması bekleniyor…",
        hud_footer = "{key} ayarlar | oyuncu hasarı {player} | sohbet {chat}",
    },
    ["vi"] = {
        hud_settings_title = "DPS KỸ NĂNG PAL | CÀI ĐẶT",
        hud_settings_note = "Cài đặt được tự động lưu. Sát thương người chơi áp dụng từ đòn đánh tiếp theo.",
        hud_settings_footer = "↑↓ chọn  ←→/Enter đổi  {key} đóng",
        hud_setting_language = "Ngôn ngữ", hud_setting_show = "Hiện bảng DPS kỹ năng",
        hud_setting_player = "Tính sát thương người chơi/vũ khí", hud_setting_detail = "Mức chi tiết",
        hud_setting_internal = "Hiện mã kỹ năng nội bộ", hud_setting_anchor = "Vị trí bảng",
        hud_setting_scale = "Tỉ lệ bảng", hud_setting_keep = "Giữ kết quả sau trận",
        hud_setting_chat = "Xuất ra chat", hud_setting_reset = "Đặt lại bài thử hiện tại",
        hud_value_on = "BẬT", hud_value_off = "TẮT", hud_value_compact = "GỌN",
        hud_value_full = "ĐẦY ĐỦ", hud_value_top_left = "TRÊN TRÁI", hud_value_top_right = "TRÊN PHẢI",
        hud_value_summary = "TÓM TẮT", hud_value_press_enter = "NHẤN ENTER", hud_value_follow_game = "Theo ngôn ngữ game",
        hud_title = "DPS KỸ NĂNG PAL | PHÒNG THỬ SÁT THƯƠNG", hud_state_finished = "HOÀN TẤT", hud_state_live = "ĐANG GHI",
        hud_summary = "{state} | {boss} | {seconds}giây | sát thương {damage} | DPS trận {dps}",
        hud_source = "[{source}] sát thương {damage} | DPS {dps} | trúng {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} sát thương | {dps} DPS | {casts} lần dùng",
        hud_skill_primary = "  {rank}. {skill} | sát thương {damage} | DPS trận {dps} | trúng {hits} | dùng {casts}",
        hud_skill_timing = "     sát thương/lần {per_cast} | động tác {action}giây | DPS lần dùng {cast_dps} | đo đủ {complete}/{casts}",
        hud_skill_cooldown = "     CD bảng {panel}giây | khoảng thực {interval}giây | chờ AI/tái dùng {gap}giây",
        hud_waiting = "Đang chờ kỹ năng Pal đánh trúng boss…",
        hud_footer = "{key} cài đặt | sát thương người chơi {player} | chat {chat}",
    },
    ["pl"] = {
        hud_settings_title = "DPS UMIEJĘTNOŚCI PALA | USTAWIENIA",
        hud_settings_note = "Ustawienia zapisują się automatycznie. Obrażenia gracza są liczone od następnego trafienia.",
        hud_settings_footer = "↑↓ wybierz  ←→/Enter zmień  {key} zamknij",
        hud_setting_language = "Język", hud_setting_show = "Pokaż panel DPS umiejętności",
        hud_setting_player = "Uwzględnij obrażenia gracza/broni", hud_setting_detail = "Poziom szczegółów",
        hud_setting_internal = "Pokaż wewnętrzny kod", hud_setting_anchor = "Pozycja panelu",
        hud_setting_scale = "Skala panelu", hud_setting_keep = "Zachowaj wynik końcowy",
        hud_setting_chat = "Wynik na czacie", hud_setting_reset = "Wyzeruj bieżący test",
        hud_value_on = "WŁ.", hud_value_off = "WYŁ.", hud_value_compact = "SKRÓT",
        hud_value_full = "PEŁNE", hud_value_top_left = "LEWY GÓRNY", hud_value_top_right = "PRAWY GÓRNY",
        hud_value_summary = "PODSUMOWANIE", hud_value_press_enter = "NACIŚNIJ ENTER", hud_value_follow_game = "Jak w grze",
        hud_title = "DPS UMIEJĘTNOŚCI PALA | TEST OBRAŻEŃ", hud_state_finished = "ZAKOŃCZONO", hud_state_live = "REJESTRACJA",
        hud_summary = "{state} | {boss} | {seconds}s | obrażenia {damage} | DPS walki {dps}",
        hud_source = "[{source}] obrażenia {damage} | DPS {dps} | trafienia {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} obrażeń | {dps} DPS | użycia {casts}",
        hud_skill_primary = "  {rank}. {skill} | obrażenia {damage} | DPS walki {dps} | trafienia {hits} | użycia {casts}",
        hud_skill_timing = "     obrażenia/użycie {per_cast} | akcja {action}s | DPS użycia {cast_dps} | pomiar {complete}/{casts}",
        hud_skill_cooldown = "     CD panelu {panel}s | realny odstęp {interval}s | przerwa AI/ponowienie {gap}s",
        hud_waiting = "Oczekiwanie, aż umiejętność Pala trafi bossa…",
        hud_footer = "{key} ustawienia | obrażenia gracza {player} | czat {chat}",
    },
}

function M.get(code, key)
    local locale = M.strings[code] or M.strings.en
    return locale[key] or M.strings.en[key]
end

function M.language_name(code)
    return M.native_names[code] or tostring(code or "")
end

return M
