local hud = {}
local unpack_args = table.unpack or unpack

local SETTINGS_FILE = "user_settings.lua"

local function safe_call(object, method_name, ...)
    if object == nil then
        return false, nil
    end
    local args = { ... }
    local ok, result = pcall(function()
        local method = object[method_name]
        if method == nil then
            return nil
        end
        return method(object, unpack_args(args))
    end)
    return ok, result
end

local function is_valid(object)
    local ok, result = safe_call(object, "IsValid")
    return ok and result == true
end

local function module_directory()
    local source = debug.getinfo(1, "S").source or ""
    if string.sub(source, 1, 1) == "@" then
        source = string.sub(source, 2)
    end
    return string.match(source, "^(.*[\\/])") or "./"
end

local function bool_text(value, chinese)
    if chinese then
        return value and "開" or "關"
    end
    return value and "ON" or "OFF"
end

local function decimal(value)
    if value == nil then
        return "—"
    end
    return string.format("%.1f", value)
end

local function integer(value)
    local number = math.floor((tonumber(value) or 0) + 0.5)
    local formatted = tostring(number)
    while true do
        local replaced, count = string.gsub(formatted, "^(-?%d+)(%d%d%d)", "%1,%2")
        formatted = replaced
        if count == 0 then
            break
        end
    end
    return formatted
end

local function chinese_language(code)
    code = tostring(code or "")
    return code == "zh-TW" or code == "zh-CN" or string.find(code, "zh", 1, true) == 1
end

local function ftext(value)
    if type(FText) == "function" then
        return FText(tostring(value or ""))
    end
    return tostring(value or "")
end

local function static_object(path)
    if type(StaticFindObject) ~= "function" then
        return nil
    end
    local ok, value = pcall(StaticFindObject, path)
    return ok and value or nil
end

local function construct(class, outer)
    if class == nil or type(StaticConstructObject) ~= "function" then
        return nil
    end
    local ok, value = pcall(StaticConstructObject, class, outer)
    return ok and value or nil
end

local function write_setting(file, key, value)
    if type(value) == "string" then
        file:write("    ", key, " = ", string.format("%q", value), ",\n")
    else
        file:write("    ", key, " = ", tostring(value), ",\n")
    end
end

function hud.new(options)
    local self = {
        config = assert(options.config),
        log = options.log or function() end,
        get_player_controller = options.get_player_controller,
        get_world_context = options.get_world_context,
        get_language = options.get_language,
        on_reset = options.on_reset,
        settings_path = module_directory() .. SETTINGS_FILE,
        settings_open = false,
        selected_setting = 1,
        widget = nil,
        panel_slot = nil,
        header_text = nil,
        summary_text = nil,
        body_text = nil,
        footer_text = nil,
        backend = "pending",
        key_label = "F1",
        latest_snapshot = nil,
        last_rendered_text = nil,
        logged_create_failure = false,
    }

    self.setting_keys = {
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
        "reset",
    }

    self.persisted_keys = {
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
    }

    function self:load_settings()
        local chunk, load_error = loadfile(self.settings_path)
        if chunk == nil then
            if load_error ~= nil and string.find(tostring(load_error), "No such file", 1, true) == nil
                and string.find(tostring(load_error), "cannot open", 1, true) == nil then
                self.log("HUD settings load skipped: " .. tostring(load_error))
            end
            return
        end
        local ok, values = pcall(chunk)
        if not ok or type(values) ~= "table" then
            self.log("HUD settings ignored: " .. tostring(values))
            return
        end
        for _, key in ipairs(self.persisted_keys) do
            if values[key] ~= nil then
                self.config[key] = values[key]
            end
        end
    end

    function self:save_settings()
        local file, open_error = io.open(self.settings_path, "w")
        if file == nil then
            self.log("HUD settings save failed: " .. tostring(open_error))
            return false
        end
        file:write("-- Generated by PalSkillDPSAnalyzer's F1 settings panel.\n")
        file:write("return {\n")
        for _, key in ipairs(self.persisted_keys) do
            write_setting(file, key, self.config[key])
        end
        file:write("}\n")
        file:close()
        return true
    end

    function self:language_code()
        if self.latest_snapshot ~= nil and self.latest_snapshot.language ~= nil then
            return self.latest_snapshot.language
        end
        if self.get_language ~= nil then
            local ok, value = pcall(self.get_language)
            if ok and value ~= nil then
                return value
            end
        end
        return self.config.Language == "auto" and "zh-TW" or self.config.Language
    end

    function self:apply_layout()
        if not is_valid(self.panel_slot) then
            return
        end
        local scale = tonumber(self.config.HUDScale) or 1.0
        scale = math.max(0.7, math.min(1.4, scale))
        local right = self.config.HUDAnchor ~= "top-left"
        safe_call(self.panel_slot, "SetAnchors", {
            Minimum = { X = right and 1 or 0, Y = 0 },
            Maximum = { X = right and 1 or 0, Y = 0 },
        })
        safe_call(self.panel_slot, "SetAlignment", { X = right and 1 or 0, Y = 0 })
        safe_call(self.panel_slot, "SetPosition", { X = right and -28 or 28, Y = 82 })
        safe_call(self.panel_slot, "SetSize", { X = 620 * scale, Y = 720 * scale })
    end

    function self:create_text_block(tree, parent, size, color)
        local text_class = static_object("/Script/UMG.TextBlock")
        local block = construct(text_class, tree)
        if not is_valid(block) then
            return nil
        end
        local added = select(2, safe_call(parent, "AddChild", block))
        if added == nil then
            return nil
        end
        safe_call(block, "SetColorAndOpacity", {
            SpecifiedColor = color,
            ColorUseRule = 0,
        })
        safe_call(block, "SetShadowOffset", { X = 1, Y = 1 })
        safe_call(block, "SetShadowColorAndOpacity", { R = 0, G = 0, B = 0, A = 0.8 })
        safe_call(block, "SetAutoWrapText", false)
        local font_ok, font = pcall(function() return block.Font end)
        if font_ok and font ~= nil then
            pcall(function() font.Size = size end)
            pcall(function() block.Font = font end)
        end
        return block
    end

    function self:create_widget()
        if is_valid(self.widget) then
            return true
        end
        local controller = self.get_player_controller and self.get_player_controller() or nil
        if not is_valid(controller) then
            return false
        end

        local library = static_object("/Script/UMG.Default__WidgetBlueprintLibrary")
        local widget_class = static_object("/Script/Pal.PalDamageDisplayCanvas")
            or static_object("/Script/UMG.UserWidget")
        local tree_class = static_object("/Script/UMG.WidgetTree")
        local canvas_class = static_object("/Script/UMG.CanvasPanel")
        local border_class = static_object("/Script/UMG.Border")
        local vertical_class = static_object("/Script/UMG.VerticalBox")
        if library == nil or widget_class == nil or tree_class == nil
            or canvas_class == nil or border_class == nil or vertical_class == nil then
            return false
        end

        local create_ok, widget = safe_call(library, "Create", controller, widget_class, controller)
        if not create_ok or not is_valid(widget) then
            return false
        end
        local tree = construct(tree_class, widget)
        local canvas = construct(canvas_class, tree)
        local border = construct(border_class, tree)
        local vertical = construct(vertical_class, tree)
        if not is_valid(tree) or not is_valid(canvas) or not is_valid(border)
            or not is_valid(vertical) then
            safe_call(widget, "RemoveFromParent")
            return false
        end

        local assigned = pcall(function()
            widget.WidgetTree = tree
            tree.RootWidget = canvas
        end)
        if not assigned then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        local slot_ok, panel_slot = safe_call(canvas, "AddChild", border)
        if not slot_ok or not is_valid(panel_slot) then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        safe_call(border, "SetContent", vertical)
        safe_call(border, "SetPadding", { Left = 16, Top = 12, Right = 16, Bottom = 12 })
        safe_call(border, "SetBrushColor", { R = 0.018, G = 0.055, B = 0.075, A = 0.92 })
        safe_call(border, "SetHorizontalAlignment", 0)
        safe_call(border, "SetVerticalAlignment", 0)

        local header = self:create_text_block(tree, vertical, 21, { R = 0.35, G = 0.92, B = 1, A = 1 })
        local summary = self:create_text_block(tree, vertical, 16, { R = 0.93, G = 0.96, B = 1, A = 1 })
        local body = self:create_text_block(tree, vertical, 15, { R = 0.88, G = 0.92, B = 0.95, A = 1 })
        local footer = self:create_text_block(tree, vertical, 13, { R = 0.52, G = 0.72, B = 0.78, A = 1 })
        if not is_valid(header) or not is_valid(summary) or not is_valid(body) or not is_valid(footer) then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        safe_call(widget, "AddToViewport", 950)
        safe_call(widget, "SetVisibility", 3)

        self.widget = widget
        self.panel_slot = panel_slot
        self.header_text = header
        self.summary_text = summary
        self.body_text = body
        self.footer_text = footer
        self.backend = "umg"
        self:apply_layout()
        self.log("HUD backend=umg hotkey=" .. self.key_label)
        return true
    end

    function self:render_text(header, summary, body, footer)
        local combined = table.concat({ header, summary, body, footer }, "\n")
        if self.last_rendered_text == combined and self.backend == "umg" then
            return
        end
        self.last_rendered_text = combined

        if self:create_widget() then
            safe_call(self.widget, "SetVisibility", 3)
            safe_call(self.header_text, "SetText", ftext(header))
            safe_call(self.summary_text, "SetText", ftext(summary))
            safe_call(self.body_text, "SetText", ftext(body))
            safe_call(self.footer_text, "SetText", ftext(footer))
            return
        end

        if not self.logged_create_failure then
            self.logged_create_failure = true
            self.log("HUD UMG creation unavailable; using on-screen text fallback")
        end
        self.backend = "screen-text"
        if self.config.HUDUseScreenTextFallback == false then
            return
        end
        local library = static_object("/Script/Engine.Default__KismetSystemLibrary")
        local world = self.get_world_context and self.get_world_context() or nil
        if library == nil or not is_valid(world) then
            return
        end
        local key = type(FName) == "function" and FName("PalSkillDPSHUD") or "PalSkillDPSHUD"
        safe_call(
            library,
            "PrintString",
            world,
            combined,
            true,
            false,
            { R = 0.35, G = 0.92, B = 1, A = 1 },
            math.max(0.6, (tonumber(self.config.HUDRefreshMilliseconds) or 500) / 1000 + 0.15),
            key
        )
    end

    function self:hide()
        if is_valid(self.widget) then
            safe_call(self.widget, "SetVisibility", 1)
        end
        self.last_rendered_text = nil
    end

    function self:settings_lines()
        local language = self:language_code()
        local chinese = chinese_language(language)
        local labels = chinese and {
            EnableSkillDPSHUD = "顯示技能 DPS 面板",
            IncludePlayerDamage = "納入人物／武器傷害",
            HUDDetailMode = "資料密度",
            HUDShowInternalSkillCode = "顯示內部英文代碼",
            HUDAnchor = "面板位置",
            HUDScale = "面板縮放",
            HUDKeepFinalResults = "戰後保留結果",
            SkillDiagnosticChatMode = "聊天輸出",
            reset = "清除本場測試",
        } or {
            EnableSkillDPSHUD = "Show skill DPS panel",
            IncludePlayerDamage = "Include player/weapon damage",
            HUDDetailMode = "Detail mode",
            HUDShowInternalSkillCode = "Show internal skill code",
            HUDAnchor = "Panel position",
            HUDScale = "Panel scale",
            HUDKeepFinalResults = "Keep final result",
            SkillDiagnosticChatMode = "Chat output",
            reset = "Reset current test",
        }
        local function value_text(key)
            local value = self.config[key]
            if key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
                or key == "HUDShowInternalSkillCode"
                or key == "HUDKeepFinalResults" then
                return bool_text(value == true, chinese)
            elseif key == "HUDDetailMode" then
                return chinese and (value == "compact" and "精簡" or "完整")
                    or (value == "compact" and "COMPACT" or "FULL")
            elseif key == "HUDAnchor" then
                return chinese and (value == "top-left" and "左上" or "右上")
                    or (value == "top-left" and "TOP LEFT" or "TOP RIGHT")
            elseif key == "HUDScale" then
                return string.format("%d%%", math.floor((tonumber(value) or 1) * 100 + 0.5))
            elseif key == "SkillDiagnosticChatMode" then
                if chinese then
                    return value == "full" and "完整" or value == "summary" and "摘要" or "關"
                end
                return string.upper(tostring(value or "off"))
            end
            return chinese and "按 Enter" or "PRESS ENTER"
        end
        local lines = {}
        for index, key in ipairs(self.setting_keys) do
            lines[#lines + 1] = string.format(
                "%s %-24s  %s",
                index == self.selected_setting and "▶" or " ",
                labels[key],
                value_text(key)
            )
        end
        return lines, chinese
    end

    function self:render_settings()
        local lines, chinese = self:settings_lines()
        self:render_text(
            chinese and "帕魯技能 DPS｜設定" or "PAL SKILL DPS | SETTINGS",
            chinese and "設定會自動儲存；人物傷害切換從下一次命中開始生效。"
                or "Settings save automatically. Player damage applies from the next hit.",
            table.concat(lines, "\n"),
            chinese and ("↑↓ 選擇　←→／Enter 調整　" .. self.key_label .. " 關閉")
                or ("UP/DOWN select  LEFT/RIGHT/ENTER change  " .. self.key_label .. " close")
        )
    end

    function self:cycle_selected(direction)
        local key = self.setting_keys[self.selected_setting]
        if key == "reset" then
            if self.on_reset ~= nil then
                self.on_reset()
            end
            return
        elseif key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
            or key == "HUDShowInternalSkillCode"
            or key == "HUDKeepFinalResults" then
            self.config[key] = self.config[key] ~= true
        elseif key == "HUDDetailMode" then
            self.config[key] = self.config[key] == "compact" and "full" or "compact"
        elseif key == "HUDAnchor" then
            self.config[key] = self.config[key] == "top-left" and "top-right" or "top-left"
        elseif key == "HUDScale" then
            local values = { 0.8, 1.0, 1.2 }
            local current = tonumber(self.config[key]) or 1.0
            local index = 2
            for candidate_index, value in ipairs(values) do
                if math.abs(value - current) < 0.05 then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        elseif key == "SkillDiagnosticChatMode" then
            local values = { "off", "summary", "full" }
            local index = 1
            for candidate_index, value in ipairs(values) do
                if value == self.config[key] then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        end
        self:save_settings()
        self:apply_layout()
    end

    function self:toggle_settings()
        self.settings_open = not self.settings_open
        self.last_rendered_text = nil
        if self.settings_open then
            self:render_settings()
        elseif self.latest_snapshot ~= nil and self.config.EnableSkillDPSHUD == true then
            self:publish(self.latest_snapshot)
        else
            self:hide()
        end
    end

    function self:register_keybinds()
        local register_async = type(RegisterKeyBindAsync) == "function"
        local register_function = register_async and RegisterKeyBindAsync or RegisterKeyBind
        if type(register_function) ~= "function" or type(Key) ~= "table" then
            self.log("HUD keybind unavailable")
            return false
        end
        local modifiers = nil
        local occupied = false
        if type(IsKeyBindRegistered) == "function" then
            local ok, result = pcall(IsKeyBindRegistered, Key.F1, {})
            occupied = ok and result == true
        end
        if occupied and type(ModifierKey) == "table" then
            modifiers = { ModifierKey.CONTROL }
            self.key_label = "Ctrl+F1"
        end
        local function register(key, key_modifiers, callback)
            key_modifiers = key_modifiers or {}
            if register_async or #key_modifiers > 0 then
                register_function(key, key_modifiers, callback)
            else
                register_function(key, callback)
            end
        end
        local function in_game(callback)
            return function()
                if type(ExecuteInGameThread) == "function" then
                    ExecuteInGameThread(callback)
                end
                return self.settings_open
            end
        end
        local ok, register_error = pcall(function()
            register(Key.F1, modifiers, in_game(function() self:toggle_settings() end))
            register(Key.UP_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = ((self.selected_setting - 2) % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            register(Key.DOWN_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = (self.selected_setting % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            for _, key in ipairs({ Key.LEFT_ARROW, Key.RIGHT_ARROW, Key.RETURN }) do
                local bound_key = key
                register(bound_key, {}, in_game(function()
                    if not self.settings_open then return end
                    self:cycle_selected(bound_key == Key.LEFT_ARROW and -1 or 1)
                    self.last_rendered_text = nil
                    self:render_settings()
                end))
            end
        end)
        if not ok then
            self.log("HUD keybind registration failed: " .. tostring(register_error))
            return false
        end
        self.log("HUD settings hotkey=" .. self.key_label)
        return true
    end

    function self:format_snapshot(snapshot)
        local chinese = chinese_language(snapshot.language)
        local final = snapshot.state == "finished"
        local header = chinese and "帕魯技能 DPS｜傷害驗證" or "PAL SKILL DPS | DAMAGE LAB"
        local state = final and (chinese and "完成" or "FINISHED") or (chinese and "記錄中" or "LIVE")
        local summary = chinese
            and string.format(
                "%s｜%s｜%.1f秒｜總傷害 %s｜整場 DPS %s",
                state, snapshot.boss, snapshot.duration, integer(snapshot.total_damage), decimal(snapshot.encounter_dps)
            )
            or string.format(
                "%s | %s | %.1fs | damage %s | encounter DPS %s",
                state, snapshot.boss, snapshot.duration, integer(snapshot.total_damage), decimal(snapshot.encounter_dps)
            )
        local lines = {}
        local shown = 0
        local maximum = math.max(1, math.floor(tonumber(self.config.HUDMaxSkillRows) or 6))
        for _, source in ipairs(snapshot.sources or {}) do
            if shown >= maximum then break end
            lines[#lines + 1] = chinese
                and string.format("【%s】傷害 %s｜DPS %s｜命中 %d", source.name, integer(source.damage), decimal(source.dps), source.hits)
                or string.format("[%s] damage %s | DPS %s | hits %d", source.name, integer(source.damage), decimal(source.dps), source.hits)
            for _, skill in ipairs(source.skills or {}) do
                if shown >= maximum then break end
                shown = shown + 1
                local skill_name = tostring(skill.name or skill.internal_code or "UNKNOWN")
                local internal_code = tostring(skill.internal_code or "")
                if self.config.HUDShowInternalSkillCode == true
                    and internal_code ~= "" and internal_code ~= skill_name then
                    skill_name = chinese
                        and (skill_name .. "（" .. internal_code .. "）")
                        or (skill_name .. " (" .. internal_code .. ")")
                end
                if self.config.HUDDetailMode == "compact" then
                    lines[#lines + 1] = chinese
                        and string.format("  %d. %s｜%s 傷害｜%s DPS｜%d次", shown, skill_name, integer(skill.damage), decimal(skill.encounter_dps), skill.casts)
                        or string.format("  %d. %s | %s dmg | %s DPS | %d casts", shown, skill_name, integer(skill.damage), decimal(skill.encounter_dps), skill.casts)
                elseif chinese then
                    lines[#lines + 1] = string.format(
                        "  %d. %s｜傷害 %s｜整場DPS %s｜命中 %d｜施放 %d",
                        shown, skill_name, integer(skill.damage), decimal(skill.encounter_dps), skill.hits, skill.casts
                    )
                    lines[#lines + 1] = string.format(
                        "     每次 %s｜動作 %s秒｜施放DPS %s｜完整計時 %d/%d",
                        decimal(skill.damage_per_cast), decimal(skill.action_duration), decimal(skill.action_dps),
                        skill.lifecycle_complete, skill.casts
                    )
                    lines[#lines + 1] = string.format(
                        "     面板CD %s秒｜實際間隔 %s秒｜AI／再用空窗 %s秒",
                        decimal(skill.panel_cd), decimal(skill.actual_interval), decimal(skill.reuse_gap)
                    )
                else
                    lines[#lines + 1] = string.format(
                        "  %d. %s | damage %s | encounter DPS %s | hits %d | casts %d",
                        shown, skill_name, integer(skill.damage), decimal(skill.encounter_dps), skill.hits, skill.casts
                    )
                    lines[#lines + 1] = string.format(
                        "     damage/cast %s | action %ss | cast DPS %s | timing %d/%d",
                        decimal(skill.damage_per_cast), decimal(skill.action_duration), decimal(skill.action_dps),
                        skill.lifecycle_complete, skill.casts
                    )
                    lines[#lines + 1] = string.format(
                        "     panel CD %ss | actual interval %ss | AI/reuse gap %ss",
                        decimal(skill.panel_cd), decimal(skill.actual_interval), decimal(skill.reuse_gap)
                    )
                end
            end
        end
        if shown == 0 then
            lines[#lines + 1] = chinese and "等待帕魯技能命中 Boss…" or "Waiting for a Pal skill to hit the boss..."
        end
        local footer = chinese
            and (self.key_label .. " 設定｜人物傷害 " .. bool_text(snapshot.include_player, true) .. "｜聊天 " .. tostring(self.config.SkillDiagnosticChatMode or "off"))
            or (self.key_label .. " settings | player damage " .. bool_text(snapshot.include_player, false) .. " | chat " .. tostring(self.config.SkillDiagnosticChatMode or "off"))
        return header, summary, table.concat(lines, "\n"), footer
    end

    function self:publish(snapshot)
        self.latest_snapshot = snapshot
        if self.settings_open then
            self:render_settings()
            return
        end
        if self.config.EnableSkillDPSHUD ~= true then
            self:hide()
            return
        end
        if snapshot.state == "finished" and self.config.HUDKeepFinalResults ~= true then
            self:hide()
            return
        end
        local header, summary, body, footer = self:format_snapshot(snapshot)
        self:render_text(header, summary, body, footer)
    end

    function self:clear()
        self.latest_snapshot = nil
        if not self.settings_open then
            self:hide()
        end
    end

    self:load_settings()
    return self
end

return hud
