local hud = {}

local SETTINGS_FILE = "user_settings.lua"
local STATE_FILE = "skill_dps_hud_state.txt"
local OVERLAY_SCRIPT = "skill_dps_overlay.ps1"

local function module_directory()
    local source = debug.getinfo(1, "S").source or ""
    if string.sub(source, 1, 1) == "@" then
        source = string.sub(source, 2)
    end
    return string.match(source, "^(.*[\\/])") or "./"
end

local function decimal(value)
    if value == nil then
        return "—"
    end
    return string.format("%.1f", value)
end

local function integer(value)
    local number = math.floor((tonumber(value) or 0) + 0.5)
    local formatted = tostring(number)
    while true do
        local replaced, count = string.gsub(formatted, "^(-?%d+)(%d%d%d)", "%1,%2")
        formatted = replaced
        if count == 0 then
            break
        end
    end
    return formatted
end

local function write_setting(file, key, value)
    if type(value) == "string" then
        file:write("    ", key, " = ", string.format("%q", value), ",\n")
    else
        file:write("    ", key, " = ", tostring(value), ",\n")
    end
end

function hud.new(options)
    local self = {
        config = assert(options.config),
        log = options.log or function() end,
        get_player_controller = options.get_player_controller,
        get_world_context = options.get_world_context,
        get_language = options.get_language,
        get_language_name = options.get_language_name,
        language_options = options.language_options or { "auto", "zh-TW", "en" },
        translate = options.translate,
        get_skill_name = options.get_skill_name,
        on_reset = options.on_reset,
        settings_path = module_directory() .. SETTINGS_FILE,
        state_path = module_directory() .. STATE_FILE,
        overlay_script_path = module_directory() .. OVERLAY_SCRIPT,
        settings_open = false,
        selected_setting = 1,
        backend = "pending",
        key_label = "F1",
        latest_snapshot = nil,
        last_rendered_text = nil,
        logged_create_failure = false,
        overlay_launch_attempted = false,
        state_sequence = 0,
    }

    self.setting_keys = {
        "Language",
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
        "reset",
    }

    self.persisted_keys = {
        "Language",
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
    }

    function self:load_settings()
        local chunk, load_error = loadfile(self.settings_path)
        if chunk == nil then
            if load_error ~= nil and string.find(tostring(load_error), "No such file", 1, true) == nil
                and string.find(tostring(load_error), "cannot open", 1, true) == nil then
                self.log("HUD settings load skipped: " .. tostring(load_error))
            end
            return
        end
        local ok, values = pcall(chunk)
        if not ok or type(values) ~= "table" then
            self.log("HUD settings ignored: " .. tostring(values))
            return
        end
        for _, key in ipairs(self.persisted_keys) do
            if values[key] ~= nil then
                self.config[key] = values[key]
            end
        end
    end

    function self:save_settings()
        local file, open_error = io.open(self.settings_path, "w")
        if file == nil then
            self.log("HUD settings save failed: " .. tostring(open_error))
            return false
        end
        file:write("-- Generated by PalSkillDPSAnalyzer's F1 settings panel.\n")
        file:write("return {\n")
        for _, key in ipairs(self.persisted_keys) do
            write_setting(file, key, self.config[key])
        end
        file:write("}\n")
        file:close()
        return true
    end

    function self:write_external_state(text, visible)
        self.state_sequence = self.state_sequence + 1
        if rawget(_G, "__BOSS_DPS_TEST") == true then
            self.last_external_state = {
                text = tostring(text or ""),
                visible = visible == true,
                sequence = self.state_sequence,
            }
            return true
        end
        local temporary_path = self.state_path .. ".tmp"
        local file, open_error = io.open(temporary_path, "wb")
        if file == nil then
            self.log("external HUD state write failed: " .. tostring(open_error))
            return false
        end
        file:write("PAL_SKILL_DPS_HUD_V1\n")
        file:write("sequence=", tostring(self.state_sequence), "\n")
        file:write("visible=", visible == true and "1" or "0", "\n")
        file:write("anchor=", tostring(self.config.HUDAnchor or "top-right"), "\n")
        file:write("scale=", tostring(tonumber(self.config.HUDScale) or 1.0), "\n")
        file:write("settings=", self.settings_open and "1" or "0", "\n")
        file:write("---\n")
        file:write(tostring(text or ""))
        file:write("\n")
        file:close()

        os.remove(self.state_path)
        local renamed, rename_error = os.rename(temporary_path, self.state_path)
        if not renamed then
            self.log("external HUD state replace failed: " .. tostring(rename_error))
            return false
        end
        return true
    end

    function self:start_external_overlay()
        if self.overlay_launch_attempted then
            return self.backend == "external-file"
        end
        self.overlay_launch_attempted = true
        self.backend = "external-file"
        if self.config.ExternalHUDAutoLaunch ~= true then
            self.log("HUD backend=external-file; automatic overlay launch disabled")
            return true
        end
        if rawget(_G, "__BOSS_DPS_TEST") == true then
            return true
        end
        local probe = io.open(self.overlay_script_path, "rb")
        if probe == nil then
            self.log("external HUD script missing: " .. self.overlay_script_path)
            return false
        end
        probe:close()

        local system_root = os.getenv("SystemRoot") or "C:\\Windows"
        local powershell = system_root .. "\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        local command = string.format(
            'cmd.exe /d /c start "" /b "%s" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -STA -File "%s" -StatePath "%s"',
            powershell,
            self.overlay_script_path,
            self.state_path
        )
        local launched, launch_kind, launch_code = os.execute(command)
        if launched == nil or launched == false then
            self.log("external HUD launch failed: " .. tostring(launch_kind or launch_code))
            return false
        end
        self.log("HUD backend=external-file; all Unreal UI calls disabled")
        return true
    end

    function self:initialize_external()
        if self.config.EnableExternalHUD ~= true then
            self.backend = "file-only"
            self.log("HUD backend=file-only; external overlay disabled")
            return false
        end
        self:start_external_overlay()
        return self:write_external_state("", false)
    end

    function self:language_code()
        if self.get_language ~= nil then
            local ok, value = pcall(self.get_language)
            if ok and value ~= nil then
                return value
            end
        end
        if self.latest_snapshot ~= nil and self.latest_snapshot.language ~= nil then
            return self.latest_snapshot.language
        end
        return self.config.Language == "auto" and "en" or self.config.Language
    end

    function self:text(key, values)
        if self.translate ~= nil then
            local ok, value = pcall(self.translate, key, values)
            if ok and value ~= nil then
                return tostring(value)
            end
        end
        return tostring(key)
    end

    function self:language_name(code)
        if code == "auto" then
            return self:text("hud_value_follow_game")
        end
        if self.get_language_name ~= nil then
            local ok, value = pcall(self.get_language_name, code)
            if ok and value ~= nil and value ~= "" then
                return tostring(value)
            end
        end
        return tostring(code or "")
    end

    function self:bool_text(value)
        return self:text(value and "hud_value_on" or "hud_value_off")
    end

    function self:chat_mode_text(value)
        if value == "full" then return self:text("hud_value_full") end
        if value == "summary" then return self:text("hud_value_summary") end
        return self:text("hud_value_off")
    end

    function self:apply_layout()
        -- The external overlay reads anchor and scale from every state update.
    end

    function self:render_text(header, summary, body, footer)
        local combined = table.concat({ header, summary, body, footer }, "\n")
        if self.last_rendered_text == combined and self.backend == "external-file" then
            return
        end
        self.last_rendered_text = combined
        self.backend = self.config.EnableExternalHUD == true and "external-file" or "file-only"
        self:write_external_state(combined, true)
    end

    function self:hide()
        self:write_external_state("", false)
        self.last_rendered_text = nil
    end

    function self:settings_lines()
        local labels = {
            Language = self:text("hud_setting_language"),
            EnableSkillDPSHUD = self:text("hud_setting_show"),
            IncludePlayerDamage = self:text("hud_setting_player"),
            HUDDetailMode = self:text("hud_setting_detail"),
            HUDShowInternalSkillCode = self:text("hud_setting_internal"),
            HUDAnchor = self:text("hud_setting_anchor"),
            HUDScale = self:text("hud_setting_scale"),
            HUDKeepFinalResults = self:text("hud_setting_keep"),
            SkillDiagnosticChatMode = self:text("hud_setting_chat"),
            reset = self:text("hud_setting_reset"),
        }
        local function value_text(key)
            local value = self.config[key]
            if key == "Language" then
                return self:language_name(tostring(value or "auto"))
            elseif key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
                or key == "HUDShowInternalSkillCode"
                or key == "HUDKeepFinalResults" then
                return self:bool_text(value == true)
            elseif key == "HUDDetailMode" then
                return self:text(value == "compact" and "hud_value_compact" or "hud_value_full")
            elseif key == "HUDAnchor" then
                return self:text(value == "top-left" and "hud_value_top_left" or "hud_value_top_right")
            elseif key == "HUDScale" then
                return string.format("%d%%", math.floor((tonumber(value) or 1) * 100 + 0.5))
            elseif key == "SkillDiagnosticChatMode" then
                return self:chat_mode_text(value)
            end
            return self:text("hud_value_press_enter")
        end
        local lines = {}
        for index, key in ipairs(self.setting_keys) do
            lines[#lines + 1] = string.format(
                "%s %-24s  %s",
                index == self.selected_setting and "▶" or " ",
                labels[key],
                value_text(key)
            )
        end
        return lines
    end

    function self:render_settings()
        local lines = self:settings_lines()
        self:render_text(
            self:text("hud_settings_title"),
            self:text("hud_settings_note"),
            table.concat(lines, "\n"),
            self:text("hud_settings_footer", { key = self.key_label })
        )
    end

    function self:cycle_selected(direction)
        local key = self.setting_keys[self.selected_setting]
        if key == "reset" then
            if self.on_reset ~= nil then
                self.on_reset()
            end
            return
        elseif key == "Language" then
            local current = tostring(self.config.Language or "auto")
            local index = 1
            for candidate_index, value in ipairs(self.language_options) do
                if value == current then index = candidate_index end
            end
            index = ((index - 1 + direction) % #self.language_options) + 1
            self.config.Language = self.language_options[index]
        elseif key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
            or key == "HUDShowInternalSkillCode"
            or key == "HUDKeepFinalResults" then
            self.config[key] = self.config[key] ~= true
        elseif key == "HUDDetailMode" then
            self.config[key] = self.config[key] == "compact" and "full" or "compact"
        elseif key == "HUDAnchor" then
            self.config[key] = self.config[key] == "top-left" and "top-right" or "top-left"
        elseif key == "HUDScale" then
            local values = { 0.8, 1.0, 1.2 }
            local current = tonumber(self.config[key]) or 1.0
            local index = 2
            for candidate_index, value in ipairs(values) do
                if math.abs(value - current) < 0.05 then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        elseif key == "SkillDiagnosticChatMode" then
            local values = { "off", "summary", "full" }
            local index = 1
            for candidate_index, value in ipairs(values) do
                if value == self.config[key] then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        end
        self:save_settings()
        self:apply_layout()
    end

    function self:toggle_settings()
        self.settings_open = not self.settings_open
        self.last_rendered_text = nil
        if self.settings_open then
            self:render_settings()
        elseif self.latest_snapshot ~= nil and self.config.EnableSkillDPSHUD == true then
            self:publish(self.latest_snapshot)
        else
            self:hide()
        end
    end

    function self:register_keybinds()
        local register_async = type(RegisterKeyBindAsync) == "function"
        local register_function = register_async and RegisterKeyBindAsync or RegisterKeyBind
        if type(register_function) ~= "function" or type(Key) ~= "table" then
            self.log("HUD keybind unavailable")
            return false
        end
        local modifiers = nil
        local occupied = false
        if type(IsKeyBindRegistered) == "function" then
            local ok, result = pcall(IsKeyBindRegistered, Key.F1, {})
            occupied = ok and result == true
        end
        if occupied and type(ModifierKey) == "table" then
            modifiers = { ModifierKey.CONTROL }
            self.key_label = "Ctrl+F1"
        end
        local function register(key, key_modifiers, callback)
            key_modifiers = key_modifiers or {}
            if register_async or #key_modifiers > 0 then
                register_function(key, key_modifiers, callback)
            else
                register_function(key, callback)
            end
        end
        local function in_game(callback)
            return function()
                if type(ExecuteInGameThread) == "function" then
                    ExecuteInGameThread(callback)
                end
                return self.settings_open
            end
        end
        local ok, register_error = pcall(function()
            register(Key.F1, modifiers, in_game(function() self:toggle_settings() end))
            register(Key.UP_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = ((self.selected_setting - 2) % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            register(Key.DOWN_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = (self.selected_setting % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            for _, key in ipairs({ Key.LEFT_ARROW, Key.RIGHT_ARROW, Key.RETURN }) do
                local bound_key = key
                register(bound_key, {}, in_game(function()
                    if not self.settings_open then return end
                    self:cycle_selected(bound_key == Key.LEFT_ARROW and -1 or 1)
                    self.last_rendered_text = nil
                    self:render_settings()
                end))
            end
        end)
        if not ok then
            self.log("HUD keybind registration failed: " .. tostring(register_error))
            return false
        end
        self.log("HUD settings hotkey=" .. self.key_label)
        return true
    end

    function self:format_snapshot(snapshot)
        local final = snapshot.state == "finished"
        local header = self:text("hud_title")
        local state = self:text(final and "hud_state_finished" or "hud_state_live")
        local summary = self:text("hud_summary", {
            state = state,
            boss = snapshot.boss,
            seconds = decimal(snapshot.duration),
            damage = integer(snapshot.total_damage),
            dps = decimal(snapshot.encounter_dps),
        })
        local lines = {}
        local shown = 0
        local maximum = math.max(1, math.floor(tonumber(self.config.HUDMaxSkillRows) or 6))
        for _, source in ipairs(snapshot.sources or {}) do
            if shown >= maximum then break end
            lines[#lines + 1] = self:text("hud_source", {
                source = source.name,
                damage = integer(source.damage),
                dps = decimal(source.dps),
                hits = source.hits,
            })
            for _, skill in ipairs(source.skills or {}) do
                if shown >= maximum then break end
                shown = shown + 1
                local internal_code = tostring(skill.internal_code or "")
                local skill_name = tostring(skill.name or internal_code or "UNKNOWN")
                if self.get_skill_name ~= nil then
                    local ok, localized = pcall(
                        self.get_skill_name,
                        internal_code,
                        skill.runtime_name or skill.name
                    )
                    if ok and localized ~= nil and localized ~= "" then
                        skill_name = tostring(localized)
                    end
                end
                if self.config.HUDShowInternalSkillCode == true
                    and internal_code ~= "" and internal_code ~= skill_name then
                    skill_name = skill_name .. " (" .. internal_code .. ")"
                end
                if self.config.HUDDetailMode == "compact" then
                    lines[#lines + 1] = self:text("hud_skill_compact", {
                        rank = shown,
                        skill = skill_name,
                        damage = integer(skill.damage),
                        dps = decimal(skill.encounter_dps),
                        casts = skill.casts,
                    })
                else
                    lines[#lines + 1] = self:text("hud_skill_primary", {
                        rank = shown,
                        skill = skill_name,
                        damage = integer(skill.damage),
                        dps = decimal(skill.encounter_dps),
                        hits = skill.hits,
                        casts = skill.casts,
                    })
                    lines[#lines + 1] = self:text("hud_skill_timing", {
                        per_cast = decimal(skill.damage_per_cast),
                        action = decimal(skill.action_duration),
                        cast_dps = decimal(skill.action_dps),
                        complete = skill.lifecycle_complete,
                        casts = skill.casts,
                    })
                    lines[#lines + 1] = self:text("hud_skill_cooldown", {
                        panel = decimal(skill.panel_cd),
                        interval = decimal(skill.actual_interval),
                        gap = decimal(skill.reuse_gap),
                    })
                end
            end
        end
        if shown == 0 then
            lines[#lines + 1] = self:text("hud_waiting")
        end
        local footer = self:text("hud_footer", {
            key = self.key_label,
            player = self:bool_text(snapshot.include_player),
            chat = self:chat_mode_text(self.config.SkillDiagnosticChatMode),
        })
        return header, summary, table.concat(lines, "\n"), footer
    end

    function self:publish(snapshot)
        self.latest_snapshot = snapshot
        if self.settings_open then
            self:render_settings()
            return
        end
        if self.config.EnableSkillDPSHUD ~= true then
            self:hide()
            return
        end
        if snapshot.state == "finished" and self.config.HUDKeepFinalResults ~= true then
            self:hide()
            return
        end
        local header, summary, body, footer = self:format_snapshot(snapshot)
        self:render_text(header, summary, body, footer)
    end

    function self:clear()
        self.latest_snapshot = nil
        if not self.settings_open then
            self:hide()
        end
    end

    self:load_settings()
    return self
end

return hud
