local hud = {}
local unpack_args = table.unpack or unpack

local SETTINGS_FILE = "user_settings.lua"

local function safe_call(object, method_name, ...)
    if object == nil then
        return false, nil
    end
    local args = { ... }
    local ok, result = pcall(function()
        local method = object[method_name]
        if method == nil then
            return nil
        end
        return method(object, unpack_args(args))
    end)
    return ok, result
end

local function is_valid(object)
    local ok, result = safe_call(object, "IsValid")
    return ok and result == true
end

local function module_directory()
    local source = debug.getinfo(1, "S").source or ""
    if string.sub(source, 1, 1) == "@" then
        source = string.sub(source, 2)
    end
    return string.match(source, "^(.*[\\/])") or "./"
end

local function decimal(value)
    if value == nil then
        return "—"
    end
    return string.format("%.1f", value)
end

local function integer(value)
    local number = math.floor((tonumber(value) or 0) + 0.5)
    local formatted = tostring(number)
    while true do
        local replaced, count = string.gsub(formatted, "^(-?%d+)(%d%d%d)", "%1,%2")
        formatted = replaced
        if count == 0 then
            break
        end
    end
    return formatted
end

local function ftext(value)
    if type(FText) == "function" then
        return FText(tostring(value or ""))
    end
    return tostring(value or "")
end

local function static_object(path)
    if type(StaticFindObject) ~= "function" then
        return nil
    end
    local ok, value = pcall(StaticFindObject, path)
    return ok and value or nil
end

local function construct(class, outer)
    if class == nil or type(StaticConstructObject) ~= "function" then
        return nil
    end
    local ok, value = pcall(StaticConstructObject, class, outer)
    return ok and value or nil
end

local function write_setting(file, key, value)
    if type(value) == "string" then
        file:write("    ", key, " = ", string.format("%q", value), ",\n")
    else
        file:write("    ", key, " = ", tostring(value), ",\n")
    end
end

function hud.new(options)
    local self = {
        config = assert(options.config),
        log = options.log or function() end,
        get_player_controller = options.get_player_controller,
        get_world_context = options.get_world_context,
        get_language = options.get_language,
        get_language_name = options.get_language_name,
        language_options = options.language_options or { "auto", "zh-TW", "en" },
        translate = options.translate,
        get_skill_name = options.get_skill_name,
        on_reset = options.on_reset,
        settings_path = module_directory() .. SETTINGS_FILE,
        settings_open = false,
        selected_setting = 1,
        widget = nil,
        panel_slot = nil,
        header_text = nil,
        summary_text = nil,
        body_text = nil,
        footer_text = nil,
        backend = "pending",
        key_label = "F1",
        latest_snapshot = nil,
        last_rendered_text = nil,
        logged_create_failure = false,
    }

    self.setting_keys = {
        "Language",
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
        "reset",
    }

    self.persisted_keys = {
        "Language",
        "EnableSkillDPSHUD",
        "IncludePlayerDamage",
        "HUDDetailMode",
        "HUDShowInternalSkillCode",
        "HUDAnchor",
        "HUDScale",
        "HUDKeepFinalResults",
        "SkillDiagnosticChatMode",
    }

    function self:load_settings()
        local chunk, load_error = loadfile(self.settings_path)
        if chunk == nil then
            if load_error ~= nil and string.find(tostring(load_error), "No such file", 1, true) == nil
                and string.find(tostring(load_error), "cannot open", 1, true) == nil then
                self.log("HUD settings load skipped: " .. tostring(load_error))
            end
            return
        end
        local ok, values = pcall(chunk)
        if not ok or type(values) ~= "table" then
            self.log("HUD settings ignored: " .. tostring(values))
            return
        end
        for _, key in ipairs(self.persisted_keys) do
            if values[key] ~= nil then
                self.config[key] = values[key]
            end
        end
    end

    function self:save_settings()
        local file, open_error = io.open(self.settings_path, "w")
        if file == nil then
            self.log("HUD settings save failed: " .. tostring(open_error))
            return false
        end
        file:write("-- Generated by PalSkillDPSAnalyzer's F1 settings panel.\n")
        file:write("return {\n")
        for _, key in ipairs(self.persisted_keys) do
            write_setting(file, key, self.config[key])
        end
        file:write("}\n")
        file:close()
        return true
    end

    function self:language_code()
        if self.get_language ~= nil then
            local ok, value = pcall(self.get_language)
            if ok and value ~= nil then
                return value
            end
        end
        if self.latest_snapshot ~= nil and self.latest_snapshot.language ~= nil then
            return self.latest_snapshot.language
        end
        return self.config.Language == "auto" and "en" or self.config.Language
    end

    function self:text(key, values)
        if self.translate ~= nil then
            local ok, value = pcall(self.translate, key, values)
            if ok and value ~= nil then
                return tostring(value)
            end
        end
        return tostring(key)
    end

    function self:language_name(code)
        if code == "auto" then
            return self:text("hud_value_follow_game")
        end
        if self.get_language_name ~= nil then
            local ok, value = pcall(self.get_language_name, code)
            if ok and value ~= nil and value ~= "" then
                return tostring(value)
            end
        end
        return tostring(code or "")
    end

    function self:bool_text(value)
        return self:text(value and "hud_value_on" or "hud_value_off")
    end

    function self:chat_mode_text(value)
        if value == "full" then return self:text("hud_value_full") end
        if value == "summary" then return self:text("hud_value_summary") end
        return self:text("hud_value_off")
    end

    function self:apply_layout()
        if not is_valid(self.panel_slot) then
            return
        end
        local scale = tonumber(self.config.HUDScale) or 1.0
        scale = math.max(0.7, math.min(1.4, scale))
        local right = self.config.HUDAnchor ~= "top-left"
        safe_call(self.panel_slot, "SetAnchors", {
            Minimum = { X = right and 1 or 0, Y = 0 },
            Maximum = { X = right and 1 or 0, Y = 0 },
        })
        safe_call(self.panel_slot, "SetAlignment", { X = right and 1 or 0, Y = 0 })
        safe_call(self.panel_slot, "SetPosition", { X = right and -28 or 28, Y = 82 })
        safe_call(self.panel_slot, "SetSize", { X = 620 * scale, Y = 720 * scale })
    end

    function self:create_text_block(tree, parent, size, color)
        local text_class = static_object("/Script/UMG.TextBlock")
        local block = construct(text_class, tree)
        if not is_valid(block) then
            return nil
        end
        local added = select(2, safe_call(parent, "AddChild", block))
        if added == nil then
            return nil
        end
        safe_call(block, "SetColorAndOpacity", {
            SpecifiedColor = color,
            ColorUseRule = 0,
        })
        safe_call(block, "SetShadowOffset", { X = 1, Y = 1 })
        safe_call(block, "SetShadowColorAndOpacity", { R = 0, G = 0, B = 0, A = 0.8 })
        safe_call(block, "SetAutoWrapText", false)
        local font_ok, font = pcall(function() return block.Font end)
        if font_ok and font ~= nil then
            pcall(function() font.Size = size end)
            pcall(function() block.Font = font end)
        end
        return block
    end

    function self:create_widget()
        if is_valid(self.widget) then
            return true
        end
        local controller = self.get_player_controller and self.get_player_controller() or nil
        if not is_valid(controller) then
            return false
        end

        local library = static_object("/Script/UMG.Default__WidgetBlueprintLibrary")
        local widget_class = static_object("/Script/Pal.PalDamageDisplayCanvas")
            or static_object("/Script/UMG.UserWidget")
        local tree_class = static_object("/Script/UMG.WidgetTree")
        local canvas_class = static_object("/Script/UMG.CanvasPanel")
        local border_class = static_object("/Script/UMG.Border")
        local vertical_class = static_object("/Script/UMG.VerticalBox")
        if library == nil or widget_class == nil or tree_class == nil
            or canvas_class == nil or border_class == nil or vertical_class == nil then
            return false
        end

        local create_ok, widget = safe_call(library, "Create", controller, widget_class, controller)
        if not create_ok or not is_valid(widget) then
            return false
        end
        local tree = construct(tree_class, widget)
        local canvas = construct(canvas_class, tree)
        local border = construct(border_class, tree)
        local vertical = construct(vertical_class, tree)
        if not is_valid(tree) or not is_valid(canvas) or not is_valid(border)
            or not is_valid(vertical) then
            safe_call(widget, "RemoveFromParent")
            return false
        end

        local assigned = pcall(function()
            widget.WidgetTree = tree
            tree.RootWidget = canvas
        end)
        if not assigned then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        local slot_ok, panel_slot = safe_call(canvas, "AddChild", border)
        if not slot_ok or not is_valid(panel_slot) then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        safe_call(border, "SetContent", vertical)
        safe_call(border, "SetPadding", { Left = 16, Top = 12, Right = 16, Bottom = 12 })
        safe_call(border, "SetBrushColor", { R = 0.018, G = 0.055, B = 0.075, A = 0.92 })
        safe_call(border, "SetHorizontalAlignment", 0)
        safe_call(border, "SetVerticalAlignment", 0)

        local header = self:create_text_block(tree, vertical, 21, { R = 0.35, G = 0.92, B = 1, A = 1 })
        local summary = self:create_text_block(tree, vertical, 16, { R = 0.93, G = 0.96, B = 1, A = 1 })
        local body = self:create_text_block(tree, vertical, 15, { R = 0.88, G = 0.92, B = 0.95, A = 1 })
        local footer = self:create_text_block(tree, vertical, 13, { R = 0.52, G = 0.72, B = 0.78, A = 1 })
        if not is_valid(header) or not is_valid(summary) or not is_valid(body) or not is_valid(footer) then
            safe_call(widget, "RemoveFromParent")
            return false
        end
        safe_call(widget, "AddToViewport", 950)
        safe_call(widget, "SetVisibility", 3)

        self.widget = widget
        self.panel_slot = panel_slot
        self.header_text = header
        self.summary_text = summary
        self.body_text = body
        self.footer_text = footer
        self.backend = "umg"
        self:apply_layout()
        self.log("HUD backend=umg hotkey=" .. self.key_label)
        return true
    end

    function self:render_text(header, summary, body, footer)
        local combined = table.concat({ header, summary, body, footer }, "\n")
        if self.last_rendered_text == combined and self.backend == "umg" then
            return
        end
        self.last_rendered_text = combined

        local experimental_umg = self.config.HUDUseExperimentalUMG == true
        if experimental_umg and self:create_widget() then
            safe_call(self.widget, "SetVisibility", 3)
            safe_call(self.header_text, "SetText", ftext(header))
            safe_call(self.summary_text, "SetText", ftext(summary))
            safe_call(self.body_text, "SetText", ftext(body))
            safe_call(self.footer_text, "SetText", ftext(footer))
            return
        end

        if not self.logged_create_failure then
            self.logged_create_failure = true
            if experimental_umg then
                self.log("HUD UMG creation unavailable; using safe screen-text backend")
            else
                self.log("HUD backend=safe-screen-text; experimental UMG disabled")
            end
        end
        self.backend = "screen-text"
        if self.config.HUDUseScreenTextFallback == false then
            return
        end
        local library = static_object("/Script/Engine.Default__KismetSystemLibrary")
        local world = self.get_world_context and self.get_world_context() or nil
        if library == nil or not is_valid(world) then
            return
        end
        local key = type(FName) == "function" and FName("PalSkillDPSHUD") or "PalSkillDPSHUD"
        safe_call(
            library,
            "PrintString",
            world,
            combined,
            true,
            false,
            { R = 0.35, G = 0.92, B = 1, A = 1 },
            math.max(0.6, (tonumber(self.config.HUDRefreshMilliseconds) or 500) / 1000 + 0.15),
            key
        )
    end

    function self:hide()
        if is_valid(self.widget) then
            safe_call(self.widget, "SetVisibility", 1)
        end
        self.last_rendered_text = nil
    end

    function self:settings_lines()
        local labels = {
            Language = self:text("hud_setting_language"),
            EnableSkillDPSHUD = self:text("hud_setting_show"),
            IncludePlayerDamage = self:text("hud_setting_player"),
            HUDDetailMode = self:text("hud_setting_detail"),
            HUDShowInternalSkillCode = self:text("hud_setting_internal"),
            HUDAnchor = self:text("hud_setting_anchor"),
            HUDScale = self:text("hud_setting_scale"),
            HUDKeepFinalResults = self:text("hud_setting_keep"),
            SkillDiagnosticChatMode = self:text("hud_setting_chat"),
            reset = self:text("hud_setting_reset"),
        }
        local function value_text(key)
            local value = self.config[key]
            if key == "Language" then
                return self:language_name(tostring(value or "auto"))
            elseif key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
                or key == "HUDShowInternalSkillCode"
                or key == "HUDKeepFinalResults" then
                return self:bool_text(value == true)
            elseif key == "HUDDetailMode" then
                return self:text(value == "compact" and "hud_value_compact" or "hud_value_full")
            elseif key == "HUDAnchor" then
                return self:text(value == "top-left" and "hud_value_top_left" or "hud_value_top_right")
            elseif key == "HUDScale" then
                return string.format("%d%%", math.floor((tonumber(value) or 1) * 100 + 0.5))
            elseif key == "SkillDiagnosticChatMode" then
                return self:chat_mode_text(value)
            end
            return self:text("hud_value_press_enter")
        end
        local lines = {}
        for index, key in ipairs(self.setting_keys) do
            lines[#lines + 1] = string.format(
                "%s %-24s  %s",
                index == self.selected_setting and "▶" or " ",
                labels[key],
                value_text(key)
            )
        end
        return lines
    end

    function self:render_settings()
        local lines = self:settings_lines()
        self:render_text(
            self:text("hud_settings_title"),
            self:text("hud_settings_note"),
            table.concat(lines, "\n"),
            self:text("hud_settings_footer", { key = self.key_label })
        )
    end

    function self:cycle_selected(direction)
        local key = self.setting_keys[self.selected_setting]
        if key == "reset" then
            if self.on_reset ~= nil then
                self.on_reset()
            end
            return
        elseif key == "Language" then
            local current = tostring(self.config.Language or "auto")
            local index = 1
            for candidate_index, value in ipairs(self.language_options) do
                if value == current then index = candidate_index end
            end
            index = ((index - 1 + direction) % #self.language_options) + 1
            self.config.Language = self.language_options[index]
        elseif key == "EnableSkillDPSHUD" or key == "IncludePlayerDamage"
            or key == "HUDShowInternalSkillCode"
            or key == "HUDKeepFinalResults" then
            self.config[key] = self.config[key] ~= true
        elseif key == "HUDDetailMode" then
            self.config[key] = self.config[key] == "compact" and "full" or "compact"
        elseif key == "HUDAnchor" then
            self.config[key] = self.config[key] == "top-left" and "top-right" or "top-left"
        elseif key == "HUDScale" then
            local values = { 0.8, 1.0, 1.2 }
            local current = tonumber(self.config[key]) or 1.0
            local index = 2
            for candidate_index, value in ipairs(values) do
                if math.abs(value - current) < 0.05 then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        elseif key == "SkillDiagnosticChatMode" then
            local values = { "off", "summary", "full" }
            local index = 1
            for candidate_index, value in ipairs(values) do
                if value == self.config[key] then
                    index = candidate_index
                end
            end
            index = ((index - 1 + direction) % #values) + 1
            self.config[key] = values[index]
        end
        self:save_settings()
        self:apply_layout()
    end

    function self:toggle_settings()
        self.settings_open = not self.settings_open
        self.last_rendered_text = nil
        if self.settings_open then
            self:render_settings()
        elseif self.latest_snapshot ~= nil and self.config.EnableSkillDPSHUD == true then
            self:publish(self.latest_snapshot)
        else
            self:hide()
        end
    end

    function self:register_keybinds()
        local register_async = type(RegisterKeyBindAsync) == "function"
        local register_function = register_async and RegisterKeyBindAsync or RegisterKeyBind
        if type(register_function) ~= "function" or type(Key) ~= "table" then
            self.log("HUD keybind unavailable")
            return false
        end
        local modifiers = nil
        local occupied = false
        if type(IsKeyBindRegistered) == "function" then
            local ok, result = pcall(IsKeyBindRegistered, Key.F1, {})
            occupied = ok and result == true
        end
        if occupied and type(ModifierKey) == "table" then
            modifiers = { ModifierKey.CONTROL }
            self.key_label = "Ctrl+F1"
        end
        local function register(key, key_modifiers, callback)
            key_modifiers = key_modifiers or {}
            if register_async or #key_modifiers > 0 then
                register_function(key, key_modifiers, callback)
            else
                register_function(key, callback)
            end
        end
        local function in_game(callback)
            return function()
                if type(ExecuteInGameThread) == "function" then
                    ExecuteInGameThread(callback)
                end
                return self.settings_open
            end
        end
        local ok, register_error = pcall(function()
            register(Key.F1, modifiers, in_game(function() self:toggle_settings() end))
            register(Key.UP_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = ((self.selected_setting - 2) % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            register(Key.DOWN_ARROW, {}, in_game(function()
                if not self.settings_open then return end
                self.selected_setting = (self.selected_setting % #self.setting_keys) + 1
                self.last_rendered_text = nil
                self:render_settings()
            end))
            for _, key in ipairs({ Key.LEFT_ARROW, Key.RIGHT_ARROW, Key.RETURN }) do
                local bound_key = key
                register(bound_key, {}, in_game(function()
                    if not self.settings_open then return end
                    self:cycle_selected(bound_key == Key.LEFT_ARROW and -1 or 1)
                    self.last_rendered_text = nil
                    self:render_settings()
                end))
            end
        end)
        if not ok then
            self.log("HUD keybind registration failed: " .. tostring(register_error))
            return false
        end
        self.log("HUD settings hotkey=" .. self.key_label)
        return true
    end

    function self:format_snapshot(snapshot)
        local final = snapshot.state == "finished"
        local header = self:text("hud_title")
        local state = self:text(final and "hud_state_finished" or "hud_state_live")
        local summary = self:text("hud_summary", {
            state = state,
            boss = snapshot.boss,
            seconds = decimal(snapshot.duration),
            damage = integer(snapshot.total_damage),
            dps = decimal(snapshot.encounter_dps),
        })
        local lines = {}
        local shown = 0
        local maximum = math.max(1, math.floor(tonumber(self.config.HUDMaxSkillRows) or 6))
        for _, source in ipairs(snapshot.sources or {}) do
            if shown >= maximum then break end
            lines[#lines + 1] = self:text("hud_source", {
                source = source.name,
                damage = integer(source.damage),
                dps = decimal(source.dps),
                hits = source.hits,
            })
            for _, skill in ipairs(source.skills or {}) do
                if shown >= maximum then break end
                shown = shown + 1
                local internal_code = tostring(skill.internal_code or "")
                local skill_name = tostring(skill.name or internal_code or "UNKNOWN")
                if self.get_skill_name ~= nil then
                    local ok, localized = pcall(
                        self.get_skill_name,
                        internal_code,
                        skill.runtime_name or skill.name
                    )
                    if ok and localized ~= nil and localized ~= "" then
                        skill_name = tostring(localized)
                    end
                end
                if self.config.HUDShowInternalSkillCode == true
                    and internal_code ~= "" and internal_code ~= skill_name then
                    skill_name = skill_name .. " (" .. internal_code .. ")"
                end
                if self.config.HUDDetailMode == "compact" then
                    lines[#lines + 1] = self:text("hud_skill_compact", {
                        rank = shown,
                        skill = skill_name,
                        damage = integer(skill.damage),
                        dps = decimal(skill.encounter_dps),
                        casts = skill.casts,
                    })
                else
                    lines[#lines + 1] = self:text("hud_skill_primary", {
                        rank = shown,
                        skill = skill_name,
                        damage = integer(skill.damage),
                        dps = decimal(skill.encounter_dps),
                        hits = skill.hits,
                        casts = skill.casts,
                    })
                    lines[#lines + 1] = self:text("hud_skill_timing", {
                        per_cast = decimal(skill.damage_per_cast),
                        action = decimal(skill.action_duration),
                        cast_dps = decimal(skill.action_dps),
                        complete = skill.lifecycle_complete,
                        casts = skill.casts,
                    })
                    lines[#lines + 1] = self:text("hud_skill_cooldown", {
                        panel = decimal(skill.panel_cd),
                        interval = decimal(skill.actual_interval),
                        gap = decimal(skill.reuse_gap),
                    })
                end
            end
        end
        if shown == 0 then
            lines[#lines + 1] = self:text("hud_waiting")
        end
        local footer = self:text("hud_footer", {
            key = self.key_label,
            player = self:bool_text(snapshot.include_player),
            chat = self:chat_mode_text(self.config.SkillDiagnosticChatMode),
        })
        return header, summary, table.concat(lines, "\n"), footer
    end

    function self:publish(snapshot)
        self.latest_snapshot = snapshot
        if self.settings_open then
            self:render_settings()
            return
        end
        if self.config.EnableSkillDPSHUD ~= true then
            self:hide()
            return
        end
        if snapshot.state == "finished" and self.config.HUDKeepFinalResults ~= true then
            self:hide()
            return
        end
        local header, summary, body, footer = self:format_snapshot(snapshot)
        self:render_text(header, summary, body, footer)
    end

    function self:clear()
        self.latest_snapshot = nil
        if not self.settings_open then
            self:hide()
        end
    end

    self:load_settings()
    return self
end

return hud
