local M = {}

M.language_options = {
    "auto", "zh-TW", "en", "zh-CN", "ja", "ko", "fr", "de", "it",
    "es-ES", "es-419", "pt-BR", "ru", "id", "th", "tr", "vi", "pl",
}

M.native_names = {
    ["en"] = "English",
    ["zh-CN"] = "简体中文",
    ["zh-TW"] = "繁體中文",
    ["ja"] = "日本語",
    ["fr"] = "Français",
    ["it"] = "Italiano",
    ["de"] = "Deutsch",
    ["es-ES"] = "Español (España)",
    ["pt-BR"] = "Português (Brasil)",
    ["ru"] = "Русский",
    ["ko"] = "한국어",
    ["id"] = "Bahasa Indonesia",
    ["es-419"] = "Español (Latinoamérica)",
    ["th"] = "ไทย",
    ["tr"] = "Türkçe",
    ["vi"] = "Tiếng Việt",
    ["pl"] = "Polski",
}

M.skill_category_names = {
    ["en"] = "Basic Attack",
    ["zh-CN"] = "普攻",
    ["zh-TW"] = "普攻",
    ["ja"] = "通常攻撃",
    ["fr"] = "Attaque de base",
    ["it"] = "Attacco base",
    ["de"] = "Standardangriff",
    ["es-ES"] = "Ataque básico",
    ["pt-BR"] = "Ataque básico",
    ["ru"] = "Базовая атака",
    ["ko"] = "기본 공격",
    ["id"] = "Serangan dasar",
    ["es-419"] = "Ataque básico",
    ["th"] = "การโจมตีพื้นฐาน",
    ["tr"] = "Temel saldırı",
    ["vi"] = "Đòn đánh cơ bản",
    ["pl"] = "Atak podstawowy",
}

M.other_category_names = {
    ["en"] = "Unattributed Damage",
    ["zh-CN"] = "未归属伤害",
    ["zh-TW"] = "未歸屬傷害",
    ["ja"] = "未帰属ダメージ",
    ["fr"] = "Dégâts non attribués",
    ["it"] = "Danni non attribuiti",
    ["de"] = "Nicht zugeordneter Schaden",
    ["es-ES"] = "Daño sin atribuir",
    ["pt-BR"] = "Dano não atribuído",
    ["ru"] = "Неопределённый урон",
    ["ko"] = "미귀속 피해",
    ["id"] = "Damage tak teratribusi",
    ["es-419"] = "Daño sin atribuir",
    ["th"] = "ความเสียหายที่ยังไม่ระบุ",
    ["tr"] = "Atanamayan hasar",
    ["vi"] = "Sát thương chưa xác định",
    ["pl"] = "Nieprzypisane obrażenia",
}

M.strings = {
    ["en"] = {
        hud_settings_title = "PAL SKILL DPS | SETTINGS",
        hud_settings_note = "Open with F1 at any time. Settings save automatically; a new test starts timing on its first hit.",
        hud_settings_footer = "UP/DOWN select  LEFT/RIGHT/ENTER change  {key} close",
        hud_setting_language = "Display language",
        hud_setting_show = "Show skill DPS panel",
        hud_setting_player = "Include player/weapon damage",
        hud_setting_detail = "Detail mode",
        hud_setting_internal = "Show internal skill code",
        hud_setting_anchor = "Panel position",
        hud_setting_scale = "Panel scale",
        hud_setting_keep = "Keep final result",
        hud_setting_chat = "Chat output",
        hud_setting_reset = "Start new test (reset damage)",
        hud_value_on = "ON",
        hud_value_off = "OFF",
        hud_value_compact = "COMPACT",
        hud_value_full = "FULL",
        hud_value_top_left = "TOP LEFT",
        hud_value_top_right = "TOP RIGHT",
        hud_value_summary = "SUMMARY",
        hud_value_press_enter = "PRESS ENTER",
        hud_value_follow_game = "Follow game",
        hud_title = "PAL SKILL DPS | DAMAGE LAB",
        hud_state_finished = "FINISHED",
        hud_state_live = "LIVE",
        hud_summary = "{state} | {boss} | {seconds}s | damage {damage} | encounter DPS {dps}",
        hud_source = "[{source}] damage {damage} | DPS {dps} | hits {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dmg | {dps} DPS | {casts} casts",
        hud_skill_primary = "  {rank}. {skill} | damage {damage} | encounter DPS {dps} | hits {hits} | casts {casts}",
        hud_skill_timing = "     damage/cast {per_cast} | action {action}s | cast DPS {cast_dps} | timing {complete}/{casts}",
        hud_skill_cooldown = "     panel CD {panel}s | actual interval {interval}s | AI/reuse gap {gap}s",
        hud_waiting = "Waiting for a Pal skill to hit the boss...",
        hud_settings_unavailable = "Settings are not available yet (native panel under development).",
        hud_skill_compact_counts = "hits {hits} · casts {casts}",
        hud_footer = "{key} settings | player damage {player} | chat {chat}",
    },
    ["zh-TW"] = {
        hud_settings_title = "帕魯技能 DPS｜設定",
        hud_settings_note = "隨時按 F1 開啟；設定自動儲存，新測試會從第一下命中才開始計時。",
        hud_settings_footer = "↑↓ 選擇　←→／Enter 調整　{key} 關閉",
        hud_setting_language = "顯示語言",
        hud_setting_show = "顯示技能 DPS 面板",
        hud_setting_player = "納入人物／武器傷害",
        hud_setting_detail = "資料密度",
        hud_setting_internal = "顯示內部英文代碼",
        hud_setting_anchor = "面板位置",
        hud_setting_scale = "面板縮放",
        hud_setting_keep = "戰後保留結果",
        hud_setting_chat = "聊天輸出",
        hud_setting_reset = "開始新測試（傷害歸零）",
        hud_value_on = "開",
        hud_value_off = "關",
        hud_value_compact = "精簡",
        hud_value_full = "完整",
        hud_value_top_left = "左上",
        hud_value_top_right = "右上",
        hud_value_summary = "摘要",
        hud_value_press_enter = "按 Enter",
        hud_value_follow_game = "跟隨遊戲",
        hud_title = "帕魯技能 DPS｜傷害驗證",
        hud_state_finished = "完成",
        hud_state_live = "記錄中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜總傷害 {damage}｜整場 DPS {dps}",
        hud_source = "【{source}】傷害 {damage}｜DPS {dps}｜命中 {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} 傷害｜{dps} DPS｜{casts}次",
        hud_skill_primary = "  {rank}. {skill}｜傷害 {damage}｜整場DPS {dps}｜命中 {hits}｜施放 {casts}",
        hud_skill_timing = "     每次 {per_cast}｜動作 {action}秒｜施放DPS {cast_dps}｜完整計時 {complete}/{casts}",
        hud_skill_cooldown = "     面板CD {panel}秒｜實際間隔 {interval}秒｜AI／再用空窗 {gap}秒",
        hud_waiting = "等待帕魯技能命中 Boss…",
        hud_settings_unavailable = "設定功能尚未提供（原生設定頁開發中）。",
        hud_skill_compact_counts = "命中 {hits} · 施放 {casts}",
        hud_footer = "{key} 設定｜人物傷害 {player}｜聊天 {chat}",
    },
    ["zh-CN"] = {
        hud_settings_title = "帕鲁技能 DPS｜设置",
        hud_settings_note = "随时按 F1 打开；设置自动保存，新测试从第一下命中才开始计时。",
        hud_settings_footer = "↑↓ 选择　←→／Enter 调整　{key} 关闭",
        hud_setting_language = "显示语言",
        hud_setting_show = "显示技能 DPS 面板",
        hud_setting_player = "纳入人物／武器伤害",
        hud_setting_detail = "数据密度",
        hud_setting_internal = "显示内部英文代码",
        hud_setting_anchor = "面板位置",
        hud_setting_scale = "面板缩放",
        hud_setting_keep = "战后保留结果",
        hud_setting_chat = "聊天输出",
        hud_setting_reset = "开始新测试（伤害归零）",
        hud_value_on = "开",
        hud_value_off = "关",
        hud_value_compact = "精简",
        hud_value_full = "完整",
        hud_value_top_left = "左上",
        hud_value_top_right = "右上",
        hud_value_summary = "摘要",
        hud_value_press_enter = "按 Enter",
        hud_value_follow_game = "跟随游戏",
        hud_title = "帕鲁技能 DPS｜伤害验证",
        hud_state_finished = "完成",
        hud_state_live = "记录中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜总伤害 {damage}｜整场 DPS {dps}",
        hud_source = "【{source}】伤害 {damage}｜DPS {dps}｜命中 {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} 伤害｜{dps} DPS｜{casts}次",
        hud_skill_primary = "  {rank}. {skill}｜伤害 {damage}｜整场DPS {dps}｜命中 {hits}｜施放 {casts}",
        hud_skill_timing = "     每次 {per_cast}｜动作 {action}秒｜施放DPS {cast_dps}｜完整计时 {complete}/{casts}",
        hud_skill_cooldown = "     面板CD {panel}秒｜实际间隔 {interval}秒｜AI／再用空窗 {gap}秒",
        hud_waiting = "等待帕鲁技能命中 Boss…",
        hud_settings_unavailable = "设置功能尚未提供（原生设置页开发中）。",
        hud_skill_compact_counts = "命中 {hits} · 施放 {casts}",
        hud_footer = "{key} 设置｜人物伤害 {player}｜聊天 {chat}",
    },
    ["ja"] = {
        hud_settings_title = "パルスキル DPS｜設定",
        hud_settings_note = "設定は自動保存されます。プレイヤーダメージは次のヒットから反映されます。",
        hud_settings_footer = "↑↓ 選択　←→／Enter 変更　{key} 閉じる",
        hud_setting_language = "表示言語",
        hud_setting_show = "スキル DPS パネルを表示",
        hud_setting_player = "プレイヤー／武器ダメージを含める",
        hud_setting_detail = "表示密度",
        hud_setting_internal = "内部スキルコードを表示",
        hud_setting_anchor = "パネル位置",
        hud_setting_scale = "パネル倍率",
        hud_setting_keep = "戦闘後も結果を表示",
        hud_setting_chat = "チャット出力",
        hud_setting_reset = "現在のテストをリセット",
        hud_value_on = "オン", hud_value_off = "オフ",
        hud_value_compact = "簡易", hud_value_full = "詳細",
        hud_value_top_left = "左上", hud_value_top_right = "右上",
        hud_value_summary = "概要", hud_value_press_enter = "Enter を押す",
        hud_value_follow_game = "ゲームに合わせる",
        hud_title = "パルスキル DPS｜ダメージ検証",
        hud_state_finished = "完了", hud_state_live = "計測中",
        hud_summary = "{state}｜{boss}｜{seconds}秒｜ダメージ {damage}｜戦闘 DPS {dps}",
        hud_source = "【{source}】ダメージ {damage}｜DPS {dps}｜ヒット {hits}",
        hud_skill_compact = "  {rank}. {skill}｜{damage} ダメージ｜{dps} DPS｜{casts}回",
        hud_skill_primary = "  {rank}. {skill}｜ダメージ {damage}｜戦闘DPS {dps}｜ヒット {hits}｜発動 {casts}",
        hud_skill_timing = "     1回 {per_cast}｜動作 {action}秒｜発動DPS {cast_dps}｜完全計測 {complete}/{casts}",
        hud_skill_cooldown = "     表示CD {panel}秒｜実間隔 {interval}秒｜AI／再使用待ち {gap}秒",
        hud_waiting = "パルのスキルがボスに当たるのを待っています…",
        hud_settings_unavailable = "設定機能はまだ利用できません（ネイティブ設定ページ開発中）。",
        hud_skill_compact_counts = "命中 {hits} · 発動 {casts}",
        hud_footer = "{key} 設定｜プレイヤーダメージ {player}｜チャット {chat}",
    },
    ["ko"] = {
        hud_settings_title = "팰 스킬 DPS | 설정",
        hud_settings_note = "설정은 자동 저장됩니다. 플레이어 피해는 다음 타격부터 적용됩니다.",
        hud_settings_footer = "↑↓ 선택  ←→/Enter 변경  {key} 닫기",
        hud_setting_language = "표시 언어", hud_setting_show = "스킬 DPS 패널 표시",
        hud_setting_player = "플레이어/무기 피해 포함", hud_setting_detail = "표시 밀도",
        hud_setting_internal = "내부 스킬 코드 표시", hud_setting_anchor = "패널 위치",
        hud_setting_scale = "패널 크기", hud_setting_keep = "전투 후 결과 유지",
        hud_setting_chat = "채팅 출력", hud_setting_reset = "현재 테스트 초기화",
        hud_value_on = "켜기", hud_value_off = "끄기", hud_value_compact = "간단",
        hud_value_full = "전체", hud_value_top_left = "왼쪽 위", hud_value_top_right = "오른쪽 위",
        hud_value_summary = "요약", hud_value_press_enter = "Enter 누르기", hud_value_follow_game = "게임 언어 따르기",
        hud_title = "팰 스킬 DPS | 피해 검증", hud_state_finished = "완료", hud_state_live = "기록 중",
        hud_summary = "{state} | {boss} | {seconds}초 | 총 피해 {damage} | 전투 DPS {dps}",
        hud_source = "[{source}] 피해 {damage} | DPS {dps} | 적중 {hits}",
        hud_skill_compact = "  {rank}. {skill} | 피해 {damage} | DPS {dps} | {casts}회",
        hud_skill_primary = "  {rank}. {skill} | 피해 {damage} | 전투DPS {dps} | 적중 {hits} | 사용 {casts}",
        hud_skill_timing = "     회당 {per_cast} | 동작 {action}초 | 사용DPS {cast_dps} | 완전 측정 {complete}/{casts}",
        hud_skill_cooldown = "     표시CD {panel}초 | 실제 간격 {interval}초 | AI/재사용 공백 {gap}초",
        hud_waiting = "팰 스킬이 보스에게 적중하기를 기다리는 중…",
        hud_settings_unavailable = "설정을 아직 사용할 수 없습니다(네이티브 패널 개발 중).",
        hud_skill_compact_counts = "명중 {hits} · 시전 {casts}",
        hud_footer = "{key} 설정 | 플레이어 피해 {player} | 채팅 {chat}",
    },
    ["fr"] = {
        hud_settings_title = "DPS DES COMPÉTENCES | RÉGLAGES",
        hud_settings_note = "Les réglages sont enregistrés automatiquement. Les dégâts du joueur s'appliquent au prochain coup.",
        hud_settings_footer = "↑↓ sélectionner  ←→/Entrée modifier  {key} fermer",
        hud_setting_language = "Langue d'affichage", hud_setting_show = "Afficher le panneau DPS",
        hud_setting_player = "Inclure dégâts joueur/arme", hud_setting_detail = "Niveau de détail",
        hud_setting_internal = "Afficher le code interne", hud_setting_anchor = "Position du panneau",
        hud_setting_scale = "Échelle du panneau", hud_setting_keep = "Conserver le résultat final",
        hud_setting_chat = "Sortie du chat", hud_setting_reset = "Réinitialiser le test",
        hud_value_on = "OUI", hud_value_off = "NON", hud_value_compact = "COMPACT",
        hud_value_full = "COMPLET", hud_value_top_left = "EN HAUT À GAUCHE", hud_value_top_right = "EN HAUT À DROITE",
        hud_value_summary = "RÉSUMÉ", hud_value_press_enter = "APPUYER SUR ENTRÉE", hud_value_follow_game = "Suivre le jeu",
        hud_title = "DPS DES COMPÉTENCES | LABO DE DÉGÂTS", hud_state_finished = "TERMINÉ", hud_state_live = "EN COURS",
        hud_summary = "{state} | {boss} | {seconds}s | dégâts {damage} | DPS du combat {dps}",
        hud_source = "[{source}] dégâts {damage} | DPS {dps} | coups {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dégâts | {dps} DPS | {casts} utilisations",
        hud_skill_primary = "  {rank}. {skill} | dégâts {damage} | DPS combat {dps} | coups {hits} | utilisations {casts}",
        hud_skill_timing = "     dégâts/util. {per_cast} | action {action}s | DPS util. {cast_dps} | suivi {complete}/{casts}",
        hud_skill_cooldown = "     CD affiché {panel}s | intervalle réel {interval}s | attente IA/réutil. {gap}s",
        hud_waiting = "En attente d'une compétence de Pal touchant le boss…",
        hud_settings_unavailable = "Les réglages ne sont pas encore disponibles (panneau natif en développement).",
        hud_skill_compact_counts = "touches {hits} · lancers {casts}",
        hud_footer = "{key} réglages | dégâts joueur {player} | chat {chat}",
    },
    ["de"] = {
        hud_settings_title = "PAL-FÄHIGKEITS-DPS | EINSTELLUNGEN",
        hud_settings_note = "Einstellungen werden automatisch gespeichert. Spielerschaden gilt ab dem nächsten Treffer.",
        hud_settings_footer = "↑↓ wählen  ←→/Enter ändern  {key} schließen",
        hud_setting_language = "Anzeigesprache", hud_setting_show = "Fähigkeits-DPS anzeigen",
        hud_setting_player = "Spieler-/Waffenschaden einbeziehen", hud_setting_detail = "Detailgrad",
        hud_setting_internal = "Internen Fähigkeitencode anzeigen", hud_setting_anchor = "Panelposition",
        hud_setting_scale = "Panelgröße", hud_setting_keep = "Endergebnis behalten",
        hud_setting_chat = "Chat-Ausgabe", hud_setting_reset = "Aktuellen Test zurücksetzen",
        hud_value_on = "AN", hud_value_off = "AUS", hud_value_compact = "KOMPAKT",
        hud_value_full = "VOLL", hud_value_top_left = "OBEN LINKS", hud_value_top_right = "OBEN RECHTS",
        hud_value_summary = "ZUSAMMENFASSUNG", hud_value_press_enter = "ENTER DRÜCKEN", hud_value_follow_game = "Spiel folgen",
        hud_title = "PAL-FÄHIGKEITS-DPS | SCHADENSLABOR", hud_state_finished = "BEENDET", hud_state_live = "AKTIV",
        hud_summary = "{state} | {boss} | {seconds}s | Schaden {damage} | Kampf-DPS {dps}",
        hud_source = "[{source}] Schaden {damage} | DPS {dps} | Treffer {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} Schaden | {dps} DPS | {casts} Einsätze",
        hud_skill_primary = "  {rank}. {skill} | Schaden {damage} | Kampf-DPS {dps} | Treffer {hits} | Einsätze {casts}",
        hud_skill_timing = "     Schaden/Einsatz {per_cast} | Aktion {action}s | Einsatz-DPS {cast_dps} | Messung {complete}/{casts}",
        hud_skill_cooldown = "     Panel-CD {panel}s | reales Intervall {interval}s | KI/Wiederverwendung {gap}s",
        hud_waiting = "Warte auf einen Pal-Fähigkeitstreffer am Boss…",
        hud_settings_unavailable = "Einstellungen sind noch nicht verfügbar (natives Panel in Entwicklung).",
        hud_skill_compact_counts = "Treffer {hits} · Würfe {casts}",
        hud_footer = "{key} Einstellungen | Spielerschaden {player} | Chat {chat}",
    },
    ["it"] = {
        hud_settings_title = "DPS ABILITÀ PAL | IMPOSTAZIONI",
        hud_settings_note = "Le impostazioni vengono salvate automaticamente. I danni del giocatore valgono dal prossimo colpo.",
        hud_settings_footer = "↑↓ seleziona  ←→/Invio modifica  {key} chiudi",
        hud_setting_language = "Lingua", hud_setting_show = "Mostra pannello DPS abilità",
        hud_setting_player = "Includi danni giocatore/arma", hud_setting_detail = "Livello di dettaglio",
        hud_setting_internal = "Mostra codice abilità interno", hud_setting_anchor = "Posizione pannello",
        hud_setting_scale = "Scala pannello", hud_setting_keep = "Mantieni risultato finale",
        hud_setting_chat = "Output chat", hud_setting_reset = "Azzera test corrente",
        hud_value_on = "SÌ", hud_value_off = "NO", hud_value_compact = "COMPATTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "IN ALTO A SINISTRA", hud_value_top_right = "IN ALTO A DESTRA",
        hud_value_summary = "RIEPILOGO", hud_value_press_enter = "PREMI INVIO", hud_value_follow_game = "Segui il gioco",
        hud_title = "DPS ABILITÀ PAL | LABORATORIO DANNI", hud_state_finished = "FINITO", hud_state_live = "ATTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | danni {damage} | DPS scontro {dps}",
        hud_source = "[{source}] danni {damage} | DPS {dps} | colpi {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} danni | {dps} DPS | {casts} usi",
        hud_skill_primary = "  {rank}. {skill} | danni {damage} | DPS scontro {dps} | colpi {hits} | usi {casts}",
        hud_skill_timing = "     danni/uso {per_cast} | azione {action}s | DPS uso {cast_dps} | misure {complete}/{casts}",
        hud_skill_cooldown = "     CD pannello {panel}s | intervallo reale {interval}s | attesa IA/riuso {gap}s",
        hud_waiting = "In attesa che un'abilità Pal colpisca il boss…",
        hud_settings_unavailable = "Le impostazioni non sono ancora disponibili (pannello nativo in sviluppo).",
        hud_skill_compact_counts = "colpi {hits} · lanci {casts}",
        hud_footer = "{key} impostazioni | danni giocatore {player} | chat {chat}",
    },
    ["es-ES"] = {
        hud_settings_title = "DPS DE HABILIDADES | AJUSTES",
        hud_settings_note = "Los ajustes se guardan automáticamente. El daño del jugador se aplica desde el siguiente golpe.",
        hud_settings_footer = "↑↓ seleccionar  ←→/Intro cambiar  {key} cerrar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar panel DPS de habilidades",
        hud_setting_player = "Incluir daño de jugador/arma", hud_setting_detail = "Nivel de detalle",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posición del panel",
        hud_setting_scale = "Escala del panel", hud_setting_keep = "Conservar resultado final",
        hud_setting_chat = "Salida del chat", hud_setting_reset = "Reiniciar prueba actual",
        hud_value_on = "SÍ", hud_value_off = "NO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "ARRIBA IZQUIERDA", hud_value_top_right = "ARRIBA DERECHA",
        hud_value_summary = "RESUMEN", hud_value_press_enter = "PULSA INTRO", hud_value_follow_game = "Seguir el juego",
        hud_title = "DPS DE HABILIDADES | LABORATORIO DE DAÑO", hud_state_finished = "TERMINADO", hud_state_live = "ACTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | daño {damage} | DPS del combate {dps}",
        hud_source = "[{source}] daño {damage} | DPS {dps} | impactos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} daño | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | daño {damage} | DPS combate {dps} | impactos {hits} | usos {casts}",
        hud_skill_timing = "     daño/uso {per_cast} | acción {action}s | DPS uso {cast_dps} | medición {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Esperando que una habilidad de Pal golpee al jefe…",
        hud_settings_unavailable = "Los ajustes aún no están disponibles (panel nativo en desarrollo).",
        hud_skill_compact_counts = "impactos {hits} · usos {casts}",
        hud_footer = "{key} ajustes | daño jugador {player} | chat {chat}",
    },
    ["es-419"] = {
        hud_settings_title = "DPS DE HABILIDADES | AJUSTES",
        hud_settings_note = "Los ajustes se guardan automáticamente. El daño del jugador aplica desde el siguiente golpe.",
        hud_settings_footer = "↑↓ seleccionar  ←→/Enter cambiar  {key} cerrar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar panel DPS de habilidades",
        hud_setting_player = "Incluir daño de jugador/arma", hud_setting_detail = "Nivel de detalle",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posición del panel",
        hud_setting_scale = "Escala del panel", hud_setting_keep = "Conservar resultado final",
        hud_setting_chat = "Salida del chat", hud_setting_reset = "Reiniciar prueba actual",
        hud_value_on = "SÍ", hud_value_off = "NO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "ARRIBA IZQUIERDA", hud_value_top_right = "ARRIBA DERECHA",
        hud_value_summary = "RESUMEN", hud_value_press_enter = "PRESIONA ENTER", hud_value_follow_game = "Seguir el juego",
        hud_title = "DPS DE HABILIDADES | LABORATORIO DE DAÑO", hud_state_finished = "TERMINADO", hud_state_live = "ACTIVO",
        hud_summary = "{state} | {boss} | {seconds}s | daño {damage} | DPS del combate {dps}",
        hud_source = "[{source}] daño {damage} | DPS {dps} | impactos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} daño | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | daño {damage} | DPS combate {dps} | impactos {hits} | usos {casts}",
        hud_skill_timing = "     daño/uso {per_cast} | acción {action}s | DPS uso {cast_dps} | medición {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Esperando que una habilidad de Pal golpee al jefe…",
        hud_settings_unavailable = "Los ajustes aún no están disponibles (panel nativo en desarrollo).",
        hud_skill_compact_counts = "impactos {hits} · usos {casts}",
        hud_footer = "{key} ajustes | daño jugador {player} | chat {chat}",
    },
    ["pt-BR"] = {
        hud_settings_title = "DPS DE HABILIDADES | CONFIGURAÇÕES",
        hud_settings_note = "As configurações são salvas automaticamente. O dano do jogador vale a partir do próximo acerto.",
        hud_settings_footer = "↑↓ selecionar  ←→/Enter alterar  {key} fechar",
        hud_setting_language = "Idioma", hud_setting_show = "Mostrar painel de DPS",
        hud_setting_player = "Incluir dano de jogador/arma", hud_setting_detail = "Nível de detalhes",
        hud_setting_internal = "Mostrar código interno", hud_setting_anchor = "Posição do painel",
        hud_setting_scale = "Escala do painel", hud_setting_keep = "Manter resultado final",
        hud_setting_chat = "Saída no chat", hud_setting_reset = "Reiniciar teste atual",
        hud_value_on = "LIGADO", hud_value_off = "DESLIGADO", hud_value_compact = "COMPACTO",
        hud_value_full = "COMPLETO", hud_value_top_left = "SUPERIOR ESQUERDO", hud_value_top_right = "SUPERIOR DIREITO",
        hud_value_summary = "RESUMO", hud_value_press_enter = "PRESSIONE ENTER", hud_value_follow_game = "Seguir o jogo",
        hud_title = "DPS DE HABILIDADES | LABORATÓRIO DE DANO", hud_state_finished = "CONCLUÍDO", hud_state_live = "ATIVO",
        hud_summary = "{state} | {boss} | {seconds}s | dano {damage} | DPS do combate {dps}",
        hud_source = "[{source}] dano {damage} | DPS {dps} | acertos {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} dano | {dps} DPS | {casts} usos",
        hud_skill_primary = "  {rank}. {skill} | dano {damage} | DPS combate {dps} | acertos {hits} | usos {casts}",
        hud_skill_timing = "     dano/uso {per_cast} | ação {action}s | DPS uso {cast_dps} | medição {complete}/{casts}",
        hud_skill_cooldown = "     CD painel {panel}s | intervalo real {interval}s | espera IA/reúso {gap}s",
        hud_waiting = "Aguardando uma habilidade de Pal atingir o chefe…",
        hud_settings_unavailable = "As configurações ainda não estão disponíveis (painel nativo em desenvolvimento).",
        hud_skill_compact_counts = "acertos {hits} · usos {casts}",
        hud_footer = "{key} configurações | dano jogador {player} | chat {chat}",
    },
    ["ru"] = {
        hud_settings_title = "DPS НАВЫКОВ ПАЛА | НАСТРОЙКИ",
        hud_settings_note = "Настройки сохраняются автоматически. Урон игрока учитывается со следующего попадания.",
        hud_settings_footer = "↑↓ выбор  ←→/Enter изменить  {key} закрыть",
        hud_setting_language = "Язык", hud_setting_show = "Показывать панель DPS",
        hud_setting_player = "Учитывать урон игрока/оружия", hud_setting_detail = "Подробность",
        hud_setting_internal = "Показывать внутренний код", hud_setting_anchor = "Положение панели",
        hud_setting_scale = "Масштаб панели", hud_setting_keep = "Сохранить итог",
        hud_setting_chat = "Вывод в чат", hud_setting_reset = "Сбросить текущий тест",
        hud_value_on = "ВКЛ", hud_value_off = "ВЫКЛ", hud_value_compact = "КРАТКО",
        hud_value_full = "ПОЛНО", hud_value_top_left = "СВЕРХУ СЛЕВА", hud_value_top_right = "СВЕРХУ СПРАВА",
        hud_value_summary = "СВОДКА", hud_value_press_enter = "НАЖМИТЕ ENTER", hud_value_follow_game = "Как в игре",
        hud_title = "DPS НАВЫКОВ ПАЛА | ПРОВЕРКА УРОНА", hud_state_finished = "ЗАВЕРШЕНО", hud_state_live = "ЗАПИСЬ",
        hud_summary = "{state} | {boss} | {seconds}с | урон {damage} | DPS боя {dps}",
        hud_source = "[{source}] урон {damage} | DPS {dps} | попадания {hits}",
        hud_skill_compact = "  {rank}. {skill} | урон {damage} | DPS {dps} | применений {casts}",
        hud_skill_primary = "  {rank}. {skill} | урон {damage} | DPS боя {dps} | попаданий {hits} | применений {casts}",
        hud_skill_timing = "     урон/прим. {per_cast} | действие {action}с | DPS прим. {cast_dps} | замер {complete}/{casts}",
        hud_skill_cooldown = "     CD панели {panel}с | реальный интервал {interval}с | ожидание ИИ/повтора {gap}с",
        hud_waiting = "Ожидание попадания навыком Пала по боссу…",
        hud_settings_unavailable = "Настройки пока недоступны (нативная панель в разработке).",
        hud_skill_compact_counts = "попаданий {hits} · кастов {casts}",
        hud_footer = "{key} настройки | урон игрока {player} | чат {chat}",
    },
    ["id"] = {
        hud_settings_title = "DPS SKILL PAL | PENGATURAN",
        hud_settings_note = "Pengaturan disimpan otomatis. Damage pemain berlaku mulai hit berikutnya.",
        hud_settings_footer = "↑↓ pilih  ←→/Enter ubah  {key} tutup",
        hud_setting_language = "Bahasa tampilan", hud_setting_show = "Tampilkan panel DPS skill",
        hud_setting_player = "Sertakan damage pemain/senjata", hud_setting_detail = "Tingkat detail",
        hud_setting_internal = "Tampilkan kode skill internal", hud_setting_anchor = "Posisi panel",
        hud_setting_scale = "Skala panel", hud_setting_keep = "Simpan hasil akhir",
        hud_setting_chat = "Output chat", hud_setting_reset = "Reset tes saat ini",
        hud_value_on = "NYALA", hud_value_off = "MATI", hud_value_compact = "RINGKAS",
        hud_value_full = "LENGKAP", hud_value_top_left = "KIRI ATAS", hud_value_top_right = "KANAN ATAS",
        hud_value_summary = "RINGKASAN", hud_value_press_enter = "TEKAN ENTER", hud_value_follow_game = "Ikuti game",
        hud_title = "DPS SKILL PAL | LAB DAMAGE", hud_state_finished = "SELESAI", hud_state_live = "MEREKAM",
        hud_summary = "{state} | {boss} | {seconds}dtk | damage {damage} | DPS pertempuran {dps}",
        hud_source = "[{source}] damage {damage} | DPS {dps} | hit {hits}",
        hud_skill_compact = "  {rank}. {skill} | damage {damage} | DPS {dps} | {casts} pemakaian",
        hud_skill_primary = "  {rank}. {skill} | damage {damage} | DPS pertempuran {dps} | hit {hits} | pemakaian {casts}",
        hud_skill_timing = "     damage/pakai {per_cast} | aksi {action}dtk | DPS pakai {cast_dps} | pengukuran {complete}/{casts}",
        hud_skill_cooldown = "     CD panel {panel}dtk | interval nyata {interval}dtk | jeda AI/pakai ulang {gap}dtk",
        hud_waiting = "Menunggu skill Pal mengenai bos…",
        hud_settings_unavailable = "Pengaturan belum tersedia (panel asli sedang dikembangkan).",
        hud_skill_compact_counts = "kena {hits} · cast {casts}",
        hud_footer = "{key} pengaturan | damage pemain {player} | chat {chat}",
    },
    ["th"] = {
        hud_settings_title = "DPS สกิลพัล | ตั้งค่า",
        hud_settings_note = "บันทึกการตั้งค่าอัตโนมัติ ดาเมจผู้เล่นมีผลตั้งแต่การโจมตีครั้งถัดไป",
        hud_settings_footer = "↑↓ เลือก  ←→/Enter เปลี่ยน  {key} ปิด",
        hud_setting_language = "ภาษา", hud_setting_show = "แสดงแผง DPS สกิล",
        hud_setting_player = "รวมดาเมจผู้เล่น/อาวุธ", hud_setting_detail = "ระดับรายละเอียด",
        hud_setting_internal = "แสดงรหัสสกิลภายใน", hud_setting_anchor = "ตำแหน่งแผง",
        hud_setting_scale = "ขนาดแผง", hud_setting_keep = "เก็บผลลัพธ์หลังจบ",
        hud_setting_chat = "ข้อความแชต", hud_setting_reset = "รีเซ็ตการทดสอบนี้",
        hud_value_on = "เปิด", hud_value_off = "ปิด", hud_value_compact = "ย่อ",
        hud_value_full = "เต็ม", hud_value_top_left = "ซ้ายบน", hud_value_top_right = "ขวาบน",
        hud_value_summary = "สรุป", hud_value_press_enter = "กด Enter", hud_value_follow_game = "ตามภาษาเกม",
        hud_title = "DPS สกิลพัล | ทดสอบดาเมจ", hud_state_finished = "เสร็จสิ้น", hud_state_live = "กำลังบันทึก",
        hud_summary = "{state} | {boss} | {seconds}วิ | ดาเมจ {damage} | DPS การต่อสู้ {dps}",
        hud_source = "[{source}] ดาเมจ {damage} | DPS {dps} | โดน {hits}",
        hud_skill_compact = "  {rank}. {skill} | ดาเมจ {damage} | DPS {dps} | ใช้ {casts} ครั้ง",
        hud_skill_primary = "  {rank}. {skill} | ดาเมจ {damage} | DPS การต่อสู้ {dps} | โดน {hits} | ใช้ {casts}",
        hud_skill_timing = "     ดาเมจ/ครั้ง {per_cast} | แอ็กชัน {action}วิ | DPS ต่อครั้ง {cast_dps} | จับเวลา {complete}/{casts}",
        hud_skill_cooldown = "     CD แผง {panel}วิ | ช่วงจริง {interval}วิ | ช่องว่าง AI/ใช้ซ้ำ {gap}วิ",
        hud_waiting = "กำลังรอสกิลพัลโจมตีบอส…",
        hud_settings_unavailable = "ยังไม่มีการตั้งค่า (กำลังพัฒนาหน้าตั้งค่าดั้งเดิม)",
        hud_skill_compact_counts = "โดน {hits} · ใช้ {casts}",
        hud_footer = "{key} ตั้งค่า | ดาเมจผู้เล่น {player} | แชต {chat}",
    },
    ["tr"] = {
        hud_settings_title = "PAL YETENEK DPS | AYARLAR",
        hud_settings_note = "Ayarlar otomatik kaydedilir. Oyuncu hasarı bir sonraki vuruştan itibaren uygulanır.",
        hud_settings_footer = "↑↓ seç  ←→/Enter değiştir  {key} kapat",
        hud_setting_language = "Görüntü dili", hud_setting_show = "Yetenek DPS panelini göster",
        hud_setting_player = "Oyuncu/silah hasarını dahil et", hud_setting_detail = "Ayrıntı düzeyi",
        hud_setting_internal = "Dahili yetenek kodunu göster", hud_setting_anchor = "Panel konumu",
        hud_setting_scale = "Panel ölçeği", hud_setting_keep = "Sonucu savaş sonrası tut",
        hud_setting_chat = "Sohbet çıktısı", hud_setting_reset = "Mevcut testi sıfırla",
        hud_value_on = "AÇIK", hud_value_off = "KAPALI", hud_value_compact = "KISA",
        hud_value_full = "TAM", hud_value_top_left = "SOL ÜST", hud_value_top_right = "SAĞ ÜST",
        hud_value_summary = "ÖZET", hud_value_press_enter = "ENTER'A BAS", hud_value_follow_game = "Oyunu takip et",
        hud_title = "PAL YETENEK DPS | HASAR LABORATUVARI", hud_state_finished = "BİTTİ", hud_state_live = "KAYITTA",
        hud_summary = "{state} | {boss} | {seconds}sn | hasar {damage} | savaş DPS {dps}",
        hud_source = "[{source}] hasar {damage} | DPS {dps} | isabet {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} hasar | {dps} DPS | {casts} kullanım",
        hud_skill_primary = "  {rank}. {skill} | hasar {damage} | savaş DPS {dps} | isabet {hits} | kullanım {casts}",
        hud_skill_timing = "     hasar/kullanım {per_cast} | eylem {action}sn | kullanım DPS {cast_dps} | ölçüm {complete}/{casts}",
        hud_skill_cooldown = "     panel CD {panel}sn | gerçek aralık {interval}sn | AI/yeniden kullanım {gap}sn",
        hud_waiting = "Bir Pal yeteneğinin bossa vurması bekleniyor…",
        hud_settings_unavailable = "Ayarlar henüz kullanılamıyor (yerel panel geliştirme aşamasında).",
        hud_skill_compact_counts = "vuruş {hits} · kullanım {casts}",
        hud_footer = "{key} ayarlar | oyuncu hasarı {player} | sohbet {chat}",
    },
    ["vi"] = {
        hud_settings_title = "DPS KỸ NĂNG PAL | CÀI ĐẶT",
        hud_settings_note = "Cài đặt được tự động lưu. Sát thương người chơi áp dụng từ đòn đánh tiếp theo.",
        hud_settings_footer = "↑↓ chọn  ←→/Enter đổi  {key} đóng",
        hud_setting_language = "Ngôn ngữ", hud_setting_show = "Hiện bảng DPS kỹ năng",
        hud_setting_player = "Tính sát thương người chơi/vũ khí", hud_setting_detail = "Mức chi tiết",
        hud_setting_internal = "Hiện mã kỹ năng nội bộ", hud_setting_anchor = "Vị trí bảng",
        hud_setting_scale = "Tỉ lệ bảng", hud_setting_keep = "Giữ kết quả sau trận",
        hud_setting_chat = "Xuất ra chat", hud_setting_reset = "Đặt lại bài thử hiện tại",
        hud_value_on = "BẬT", hud_value_off = "TẮT", hud_value_compact = "GỌN",
        hud_value_full = "ĐẦY ĐỦ", hud_value_top_left = "TRÊN TRÁI", hud_value_top_right = "TRÊN PHẢI",
        hud_value_summary = "TÓM TẮT", hud_value_press_enter = "NHẤN ENTER", hud_value_follow_game = "Theo ngôn ngữ game",
        hud_title = "DPS KỸ NĂNG PAL | PHÒNG THỬ SÁT THƯƠNG", hud_state_finished = "HOÀN TẤT", hud_state_live = "ĐANG GHI",
        hud_summary = "{state} | {boss} | {seconds}giây | sát thương {damage} | DPS trận {dps}",
        hud_source = "[{source}] sát thương {damage} | DPS {dps} | trúng {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} sát thương | {dps} DPS | {casts} lần dùng",
        hud_skill_primary = "  {rank}. {skill} | sát thương {damage} | DPS trận {dps} | trúng {hits} | dùng {casts}",
        hud_skill_timing = "     sát thương/lần {per_cast} | động tác {action}giây | DPS lần dùng {cast_dps} | đo đủ {complete}/{casts}",
        hud_skill_cooldown = "     CD bảng {panel}giây | khoảng thực {interval}giây | chờ AI/tái dùng {gap}giây",
        hud_waiting = "Đang chờ kỹ năng Pal đánh trúng boss…",
        hud_settings_unavailable = "Cài đặt chưa khả dụng (đang phát triển bảng cài đặt gốc).",
        hud_skill_compact_counts = "trúng {hits} · dùng {casts}",
        hud_footer = "{key} cài đặt | sát thương người chơi {player} | chat {chat}",
    },
    ["pl"] = {
        hud_settings_title = "DPS UMIEJĘTNOŚCI PALA | USTAWIENIA",
        hud_settings_note = "Ustawienia zapisują się automatycznie. Obrażenia gracza są liczone od następnego trafienia.",
        hud_settings_footer = "↑↓ wybierz  ←→/Enter zmień  {key} zamknij",
        hud_setting_language = "Język", hud_setting_show = "Pokaż panel DPS umiejętności",
        hud_setting_player = "Uwzględnij obrażenia gracza/broni", hud_setting_detail = "Poziom szczegółów",
        hud_setting_internal = "Pokaż wewnętrzny kod", hud_setting_anchor = "Pozycja panelu",
        hud_setting_scale = "Skala panelu", hud_setting_keep = "Zachowaj wynik końcowy",
        hud_setting_chat = "Wynik na czacie", hud_setting_reset = "Wyzeruj bieżący test",
        hud_value_on = "WŁ.", hud_value_off = "WYŁ.", hud_value_compact = "SKRÓT",
        hud_value_full = "PEŁNE", hud_value_top_left = "LEWY GÓRNY", hud_value_top_right = "PRAWY GÓRNY",
        hud_value_summary = "PODSUMOWANIE", hud_value_press_enter = "NACIŚNIJ ENTER", hud_value_follow_game = "Jak w grze",
        hud_title = "DPS UMIEJĘTNOŚCI PALA | TEST OBRAŻEŃ", hud_state_finished = "ZAKOŃCZONO", hud_state_live = "REJESTRACJA",
        hud_summary = "{state} | {boss} | {seconds}s | obrażenia {damage} | DPS walki {dps}",
        hud_source = "[{source}] obrażenia {damage} | DPS {dps} | trafienia {hits}",
        hud_skill_compact = "  {rank}. {skill} | {damage} obrażeń | {dps} DPS | użycia {casts}",
        hud_skill_primary = "  {rank}. {skill} | obrażenia {damage} | DPS walki {dps} | trafienia {hits} | użycia {casts}",
        hud_skill_timing = "     obrażenia/użycie {per_cast} | akcja {action}s | DPS użycia {cast_dps} | pomiar {complete}/{casts}",
        hud_skill_cooldown = "     CD panelu {panel}s | realny odstęp {interval}s | przerwa AI/ponowienie {gap}s",
        hud_waiting = "Oczekiwanie, aż umiejętność Pala trafi bossa…",
        hud_settings_unavailable = "Ustawienia nie są jeszcze dostępne (natywny panel w trakcie tworzenia).",
        hud_skill_compact_counts = "trafienia {hits} · użycia {casts}",
        hud_footer = "{key} ustawienia | obrażenia gracza {player} | czat {chat}",
    },
}

-- v0.5.1 settings/results workspace strings. They remain supplemental so the
-- stable legacy HUD table does not need to be mechanically rewritten, while
-- every selectable Palworld language still receives a complete workspace.
M.extra_strings = {
    ["en"] = {
        hud_settings_close = "CLOSE",
        hud_tab_settings = "SETTINGS",
        hud_tab_results = "CURRENT TEST",
        hud_no_results = "No damage recorded yet. Close F1 and let a Pal land the first hit.",
        hud_group_general = "GENERAL",
        hud_group_measurement = "MEASUREMENT",
        hud_group_display = "COMBAT METER",
        hud_group_output = "RESULTS & OUTPUT",
        hud_group_test = "TEST CONTROL",
        hud_setting_measurement_mode = "Test session mode",
        hud_setting_target_scope = "Accepted targets",
        hud_setting_final_duration = "Final result duration",
        hud_value_mode_manual = "MANUAL TEST WINDOW",
        hud_value_mode_target = "ONE TEST PER TARGET",
        hud_value_scope_all = "ALL WILD PALS",
        hud_value_scope_boss = "BOSS / ALPHA ONLY",
        hud_value_left_center = "SAFE LEFT",
        hud_value_right_center = "SAFE RIGHT",
        hud_value_keep = "KEEP UNTIL NEXT TEST",
        hud_value_hide = "HIDE AT END",
        hud_value_seconds = "{seconds} SEC",
        hud_manual_test = "Manual damage test",
        hud_target_count = "{count} targets",
        hud_result_context = "{target} · {seconds}s · {count} targets",
    },
    ["zh-TW"] = {
        hud_settings_close = "關閉",
        hud_tab_settings = "設定",
        hud_tab_results = "本次測試",
        hud_no_results = "尚未記錄傷害。關閉 F1 後，讓任一隻帕魯打出第一下即可開始。",
        hud_group_general = "一般",
        hud_group_measurement = "測量方式",
        hud_group_display = "戰鬥儀表",
        hud_group_output = "結果與輸出",
        hud_group_test = "測試控制",
        hud_setting_measurement_mode = "測試分場方式",
        hud_setting_target_scope = "可測量目標",
        hud_setting_final_duration = "戰後結果顯示時間",
        hud_value_mode_manual = "手動測試區間",
        hud_value_mode_target = "每個目標自動分場",
        hud_value_scope_all = "所有野生帕魯",
        hud_value_scope_boss = "只限 Boss／頭目",
        hud_value_left_center = "左側安全區",
        hud_value_right_center = "右側安全區",
        hud_value_keep = "保留到下次測試",
        hud_value_hide = "結束即隱藏",
        hud_value_seconds = "{seconds} 秒",
        hud_manual_test = "手動傷害測試",
        hud_target_count = "{count} 個目標",
        hud_result_context = "{target}｜{seconds} 秒｜{count} 個目標",
    },
    ["zh-CN"] = {
        hud_settings_close = "关闭",
        hud_tab_settings = "设置",
        hud_tab_results = "本次测试",
        hud_no_results = "尚未记录伤害。关闭 F1 后，让任意帕鲁打出第一下即可开始。",
        hud_group_general = "一般",
        hud_group_measurement = "测量方式",
        hud_group_display = "战斗仪表",
        hud_group_output = "结果与输出",
        hud_group_test = "测试控制",
        hud_setting_measurement_mode = "测试分场方式",
        hud_setting_target_scope = "可测量目标",
        hud_setting_final_duration = "战后结果显示时间",
        hud_value_mode_manual = "手动测试区间",
        hud_value_mode_target = "每个目标自动分场",
        hud_value_scope_all = "所有野生帕鲁",
        hud_value_scope_boss = "仅 Boss／头目",
        hud_value_left_center = "左侧安全区",
        hud_value_right_center = "右侧安全区",
        hud_value_keep = "保留到下次测试",
        hud_value_hide = "结束即隐藏",
        hud_value_seconds = "{seconds} 秒",
        hud_manual_test = "手动伤害测试",
        hud_target_count = "{count} 个目标",
        hud_result_context = "{target}｜{seconds} 秒｜{count} 个目标",
    },
    ["ja"] = {
        hud_settings_close = "閉じる", hud_tab_settings = "設定", hud_tab_results = "今回のテスト",
        hud_no_results = "まだダメージは記録されていません。F1 を閉じ、パルに最初の一撃を当てさせてください。",
        hud_group_general = "一般", hud_group_measurement = "計測", hud_group_display = "戦闘メーター",
        hud_group_output = "結果と出力", hud_group_test = "テスト操作",
        hud_setting_measurement_mode = "テスト区間モード", hud_setting_target_scope = "計測対象",
        hud_setting_final_duration = "最終結果の表示時間",
        hud_value_mode_manual = "手動テスト区間", hud_value_mode_target = "対象ごとに自動計測",
        hud_value_scope_all = "すべての野生パル", hud_value_scope_boss = "ボス／アルファのみ",
        hud_value_left_center = "左セーフエリア", hud_value_right_center = "右セーフエリア",
        hud_value_keep = "次のテストまで表示", hud_value_hide = "終了時に非表示",
        hud_value_seconds = "{seconds} 秒", hud_manual_test = "手動ダメージテスト",
        hud_target_count = "対象 {count} 体", hud_result_context = "{target}・{seconds}秒・対象{count}体",
    },
    ["ko"] = {
        hud_settings_close = "닫기", hud_tab_settings = "설정", hud_tab_results = "현재 테스트",
        hud_no_results = "아직 기록된 피해가 없습니다. F1을 닫고 팰이 첫 타격을 하게 하세요.",
        hud_group_general = "일반", hud_group_measurement = "측정", hud_group_display = "전투 미터",
        hud_group_output = "결과 및 출력", hud_group_test = "테스트 제어",
        hud_setting_measurement_mode = "테스트 구간 방식", hud_setting_target_scope = "측정 대상",
        hud_setting_final_duration = "최종 결과 표시 시간",
        hud_value_mode_manual = "수동 테스트 구간", hud_value_mode_target = "대상별 자동 테스트",
        hud_value_scope_all = "모든 야생 팰", hud_value_scope_boss = "보스/알파만",
        hud_value_left_center = "왼쪽 안전 영역", hud_value_right_center = "오른쪽 안전 영역",
        hud_value_keep = "다음 테스트까지 유지", hud_value_hide = "종료 시 숨김",
        hud_value_seconds = "{seconds}초", hud_manual_test = "수동 피해 테스트",
        hud_target_count = "대상 {count}마리", hud_result_context = "{target} · {seconds}초 · 대상 {count}마리",
    },
    ["fr"] = {
        hud_settings_close = "FERMER", hud_tab_settings = "RÉGLAGES", hud_tab_results = "TEST ACTUEL",
        hud_no_results = "Aucun dégât enregistré. Fermez F1 et laissez un Pal porter le premier coup.",
        hud_group_general = "GÉNÉRAL", hud_group_measurement = "MESURE", hud_group_display = "COMPTEUR DE COMBAT",
        hud_group_output = "RÉSULTATS ET SORTIE", hud_group_test = "CONTRÔLE DU TEST",
        hud_setting_measurement_mode = "Mode de session", hud_setting_target_scope = "Cibles acceptées",
        hud_setting_final_duration = "Durée du résultat final",
        hud_value_mode_manual = "FENÊTRE MANUELLE", hud_value_mode_target = "UN TEST PAR CIBLE",
        hud_value_scope_all = "TOUS LES PALS SAUVAGES", hud_value_scope_boss = "BOSS / ALPHA UNIQUEMENT",
        hud_value_left_center = "ZONE SÛRE GAUCHE", hud_value_right_center = "ZONE SÛRE DROITE",
        hud_value_keep = "GARDER JUSQU'AU PROCHAIN TEST", hud_value_hide = "MASQUER À LA FIN",
        hud_value_seconds = "{seconds} S", hud_manual_test = "Test de dégâts manuel",
        hud_target_count = "{count} cibles", hud_result_context = "{target} · {seconds}s · {count} cibles",
    },
    ["de"] = {
        hud_settings_close = "SCHLIESSEN", hud_tab_settings = "EINSTELLUNGEN", hud_tab_results = "AKTUELLER TEST",
        hud_no_results = "Noch kein Schaden erfasst. F1 schließen und einen Pal den ersten Treffer landen lassen.",
        hud_group_general = "ALLGEMEIN", hud_group_measurement = "MESSUNG", hud_group_display = "KAMPFANZEIGE",
        hud_group_output = "ERGEBNISSE & AUSGABE", hud_group_test = "TESTSTEUERUNG",
        hud_setting_measurement_mode = "Testsitzungsmodus", hud_setting_target_scope = "Erlaubte Ziele",
        hud_setting_final_duration = "Anzeigedauer des Endergebnisses",
        hud_value_mode_manual = "MANUELLES TESTFENSTER", hud_value_mode_target = "EIN TEST PRO ZIEL",
        hud_value_scope_all = "ALLE WILDEN PALS", hud_value_scope_boss = "NUR BOSS / ALPHA",
        hud_value_left_center = "SICHERER BEREICH LINKS", hud_value_right_center = "SICHERER BEREICH RECHTS",
        hud_value_keep = "BIS ZUM NÄCHSTEN TEST", hud_value_hide = "AM ENDE AUSBLENDEN",
        hud_value_seconds = "{seconds} SEK", hud_manual_test = "Manueller Schadenstest",
        hud_target_count = "{count} Ziele", hud_result_context = "{target} · {seconds}s · {count} Ziele",
    },
    ["it"] = {
        hud_settings_close = "CHIUDI", hud_tab_settings = "IMPOSTAZIONI", hud_tab_results = "TEST ATTUALE",
        hud_no_results = "Nessun danno registrato. Chiudi F1 e lascia che un Pal metta a segno il primo colpo.",
        hud_group_general = "GENERALE", hud_group_measurement = "MISURAZIONE", hud_group_display = "MISURATORE DI COMBATTIMENTO",
        hud_group_output = "RISULTATI E OUTPUT", hud_group_test = "CONTROLLO TEST",
        hud_setting_measurement_mode = "Modalità sessione", hud_setting_target_scope = "Bersagli accettati",
        hud_setting_final_duration = "Durata risultato finale",
        hud_value_mode_manual = "FINESTRA TEST MANUALE", hud_value_mode_target = "UN TEST PER BERSAGLIO",
        hud_value_scope_all = "TUTTI I PAL SELVATICI", hud_value_scope_boss = "SOLO BOSS / ALPHA",
        hud_value_left_center = "AREA SICURA SINISTRA", hud_value_right_center = "AREA SICURA DESTRA",
        hud_value_keep = "FINO AL PROSSIMO TEST", hud_value_hide = "NASCONDI ALLA FINE",
        hud_value_seconds = "{seconds} SEC", hud_manual_test = "Test danni manuale",
        hud_target_count = "{count} bersagli", hud_result_context = "{target} · {seconds}s · {count} bersagli",
    },
    ["es-ES"] = {
        hud_settings_close = "CERRAR", hud_tab_settings = "AJUSTES", hud_tab_results = "PRUEBA ACTUAL",
        hud_no_results = "Aún no hay daño registrado. Cierra F1 y deja que un Pal dé el primer golpe.",
        hud_group_general = "GENERAL", hud_group_measurement = "MEDICIÓN", hud_group_display = "MEDIDOR DE COMBATE",
        hud_group_output = "RESULTADOS Y SALIDA", hud_group_test = "CONTROL DE PRUEBA",
        hud_setting_measurement_mode = "Modo de sesión", hud_setting_target_scope = "Objetivos admitidos",
        hud_setting_final_duration = "Duración del resultado final",
        hud_value_mode_manual = "VENTANA MANUAL", hud_value_mode_target = "UNA PRUEBA POR OBJETIVO",
        hud_value_scope_all = "TODOS LOS PALS SALVAJES", hud_value_scope_boss = "SOLO BOSS / ALPHA",
        hud_value_left_center = "ZONA SEGURA IZQUIERDA", hud_value_right_center = "ZONA SEGURA DERECHA",
        hud_value_keep = "HASTA LA SIGUIENTE PRUEBA", hud_value_hide = "OCULTAR AL TERMINAR",
        hud_value_seconds = "{seconds} S", hud_manual_test = "Prueba manual de daño",
        hud_target_count = "{count} objetivos", hud_result_context = "{target} · {seconds}s · {count} objetivos",
    },
    ["es-419"] = {
        hud_settings_close = "CERRAR", hud_tab_settings = "AJUSTES", hud_tab_results = "PRUEBA ACTUAL",
        hud_no_results = "Todavía no hay daño registrado. Cierra F1 y deja que un Pal dé el primer golpe.",
        hud_group_general = "GENERAL", hud_group_measurement = "MEDICIÓN", hud_group_display = "MEDIDOR DE COMBATE",
        hud_group_output = "RESULTADOS Y SALIDA", hud_group_test = "CONTROL DE PRUEBA",
        hud_setting_measurement_mode = "Modo de sesión", hud_setting_target_scope = "Objetivos aceptados",
        hud_setting_final_duration = "Duración del resultado final",
        hud_value_mode_manual = "VENTANA MANUAL", hud_value_mode_target = "UNA PRUEBA POR OBJETIVO",
        hud_value_scope_all = "TODOS LOS PALS SALVAJES", hud_value_scope_boss = "SOLO JEFES / ALPHA",
        hud_value_left_center = "ZONA SEGURA IZQUIERDA", hud_value_right_center = "ZONA SEGURA DERECHA",
        hud_value_keep = "HASTA LA SIGUIENTE PRUEBA", hud_value_hide = "OCULTAR AL TERMINAR",
        hud_value_seconds = "{seconds} S", hud_manual_test = "Prueba manual de daño",
        hud_target_count = "{count} objetivos", hud_result_context = "{target} · {seconds}s · {count} objetivos",
    },
    ["pt-BR"] = {
        hud_settings_close = "FECHAR", hud_tab_settings = "CONFIGURAÇÕES", hud_tab_results = "TESTE ATUAL",
        hud_no_results = "Nenhum dano registrado. Feche o F1 e deixe um Pal acertar o primeiro golpe.",
        hud_group_general = "GERAL", hud_group_measurement = "MEDIÇÃO", hud_group_display = "MEDIDOR DE COMBATE",
        hud_group_output = "RESULTADOS E SAÍDA", hud_group_test = "CONTROLE DO TESTE",
        hud_setting_measurement_mode = "Modo da sessão", hud_setting_target_scope = "Alvos aceitos",
        hud_setting_final_duration = "Duração do resultado final",
        hud_value_mode_manual = "JANELA MANUAL", hud_value_mode_target = "UM TESTE POR ALVO",
        hud_value_scope_all = "TODOS OS PALS SELVAGENS", hud_value_scope_boss = "SÓ CHEFE / ALPHA",
        hud_value_left_center = "ÁREA SEGURA ESQUERDA", hud_value_right_center = "ÁREA SEGURA DIREITA",
        hud_value_keep = "ATÉ O PRÓXIMO TESTE", hud_value_hide = "OCULTAR AO TERMINAR",
        hud_value_seconds = "{seconds} S", hud_manual_test = "Teste manual de dano",
        hud_target_count = "{count} alvos", hud_result_context = "{target} · {seconds}s · {count} alvos",
    },
    ["ru"] = {
        hud_settings_close = "ЗАКРЫТЬ", hud_tab_settings = "НАСТРОЙКИ", hud_tab_results = "ТЕКУЩИЙ ТЕСТ",
        hud_no_results = "Урон ещё не записан. Закройте F1 и дайте Палу нанести первый удар.",
        hud_group_general = "ОБЩЕЕ", hud_group_measurement = "ИЗМЕРЕНИЕ", hud_group_display = "БОЕВОЙ ИНДИКАТОР",
        hud_group_output = "РЕЗУЛЬТАТЫ И ВЫВОД", hud_group_test = "УПРАВЛЕНИЕ ТЕСТОМ",
        hud_setting_measurement_mode = "Режим тестовой сессии", hud_setting_target_scope = "Допустимые цели",
        hud_setting_final_duration = "Время показа результата",
        hud_value_mode_manual = "РУЧНОЕ ОКНО ТЕСТА", hud_value_mode_target = "ОДИН ТЕСТ НА ЦЕЛЬ",
        hud_value_scope_all = "ВСЕ ДИКИЕ ПАЛЫ", hud_value_scope_boss = "ТОЛЬКО БОСС / АЛЬФА",
        hud_value_left_center = "БЕЗОПАСНАЯ ЗОНА СЛЕВА", hud_value_right_center = "БЕЗОПАСНАЯ ЗОНА СПРАВА",
        hud_value_keep = "ДО СЛЕДУЮЩЕГО ТЕСТА", hud_value_hide = "СКРЫТЬ ПОСЛЕ ОКОНЧАНИЯ",
        hud_value_seconds = "{seconds} С", hud_manual_test = "Ручной тест урона",
        hud_target_count = "целей: {count}", hud_result_context = "{target} · {seconds}с · целей: {count}",
    },
    ["id"] = {
        hud_settings_close = "TUTUP", hud_tab_settings = "PENGATURAN", hud_tab_results = "TES SAAT INI",
        hud_no_results = "Belum ada damage tercatat. Tutup F1 dan biarkan Pal melakukan hit pertama.",
        hud_group_general = "UMUM", hud_group_measurement = "PENGUKURAN", hud_group_display = "METER PERTEMPURAN",
        hud_group_output = "HASIL & OUTPUT", hud_group_test = "KONTROL TES",
        hud_setting_measurement_mode = "Mode sesi tes", hud_setting_target_scope = "Target yang diterima",
        hud_setting_final_duration = "Durasi hasil akhir",
        hud_value_mode_manual = "JENDELA TES MANUAL", hud_value_mode_target = "SATU TES PER TARGET",
        hud_value_scope_all = "SEMUA PAL LIAR", hud_value_scope_boss = "HANYA BOSS / ALPHA",
        hud_value_left_center = "AREA AMAN KIRI", hud_value_right_center = "AREA AMAN KANAN",
        hud_value_keep = "SAMPAI TES BERIKUTNYA", hud_value_hide = "SEMBUNYIKAN SAAT SELESAI",
        hud_value_seconds = "{seconds} DTK", hud_manual_test = "Tes damage manual",
        hud_target_count = "{count} target", hud_result_context = "{target} · {seconds}dtk · {count} target",
    },
    ["th"] = {
        hud_settings_close = "ปิด", hud_tab_settings = "ตั้งค่า", hud_tab_results = "การทดสอบปัจจุบัน",
        hud_no_results = "ยังไม่มีดาเมจที่บันทึก ปิด F1 แล้วให้พัลโจมตีครั้งแรก",
        hud_group_general = "ทั่วไป", hud_group_measurement = "การวัด", hud_group_display = "มิเตอร์ต่อสู้",
        hud_group_output = "ผลลัพธ์และเอาต์พุต", hud_group_test = "ควบคุมการทดสอบ",
        hud_setting_measurement_mode = "โหมดช่วงทดสอบ", hud_setting_target_scope = "เป้าหมายที่วัด",
        hud_setting_final_duration = "เวลาที่แสดงผลสุดท้าย",
        hud_value_mode_manual = "ช่วงทดสอบแบบกำหนดเอง", hud_value_mode_target = "หนึ่งการทดสอบต่อเป้าหมาย",
        hud_value_scope_all = "พัลป่าทั้งหมด", hud_value_scope_boss = "เฉพาะบอส / อัลฟ่า",
        hud_value_left_center = "พื้นที่ปลอดภัยซ้าย", hud_value_right_center = "พื้นที่ปลอดภัยขวา",
        hud_value_keep = "เก็บจนถึงการทดสอบถัดไป", hud_value_hide = "ซ่อนเมื่อจบ",
        hud_value_seconds = "{seconds} วิ", hud_manual_test = "ทดสอบดาเมจแบบกำหนดเอง",
        hud_target_count = "{count} เป้าหมาย", hud_result_context = "{target} · {seconds}วิ · {count} เป้าหมาย",
    },
    ["tr"] = {
        hud_settings_close = "KAPAT", hud_tab_settings = "AYARLAR", hud_tab_results = "MEVCUT TEST",
        hud_no_results = "Henüz hasar kaydedilmedi. F1'i kapatın ve bir Pal'ın ilk vuruşu yapmasını sağlayın.",
        hud_group_general = "GENEL", hud_group_measurement = "ÖLÇÜM", hud_group_display = "SAVAŞ ÖLÇERİ",
        hud_group_output = "SONUÇLAR VE ÇIKTI", hud_group_test = "TEST KONTROLÜ",
        hud_setting_measurement_mode = "Test oturumu modu", hud_setting_target_scope = "Kabul edilen hedefler",
        hud_setting_final_duration = "Sonuç gösterim süresi",
        hud_value_mode_manual = "MANUEL TEST ARALIĞI", hud_value_mode_target = "HEDEF BAŞINA BİR TEST",
        hud_value_scope_all = "TÜM VAHŞİ PALLAR", hud_value_scope_boss = "YALNIZCA BOSS / ALPHA",
        hud_value_left_center = "GÜVENLİ SOL ALAN", hud_value_right_center = "GÜVENLİ SAĞ ALAN",
        hud_value_keep = "SONRAKİ TESTE KADAR", hud_value_hide = "BİTİNCE GİZLE",
        hud_value_seconds = "{seconds} SN", hud_manual_test = "Manuel hasar testi",
        hud_target_count = "{count} hedef", hud_result_context = "{target} · {seconds}sn · {count} hedef",
    },
    ["vi"] = {
        hud_settings_close = "ĐÓNG", hud_tab_settings = "CÀI ĐẶT", hud_tab_results = "BÀI THỬ HIỆN TẠI",
        hud_no_results = "Chưa ghi nhận sát thương. Đóng F1 và để một Pal tung đòn đầu tiên.",
        hud_group_general = "CHUNG", hud_group_measurement = "ĐO LƯỜNG", hud_group_display = "ĐỒNG HỒ CHIẾN ĐẤU",
        hud_group_output = "KẾT QUẢ & ĐẦU RA", hud_group_test = "ĐIỀU KHIỂN BÀI THỬ",
        hud_setting_measurement_mode = "Chế độ phiên thử", hud_setting_target_scope = "Mục tiêu được tính",
        hud_setting_final_duration = "Thời gian hiện kết quả",
        hud_value_mode_manual = "KHOẢNG THỬ THỦ CÔNG", hud_value_mode_target = "MỖI MỤC TIÊU MỘT BÀI",
        hud_value_scope_all = "TẤT CẢ PAL HOANG DÃ", hud_value_scope_boss = "CHỈ BOSS / ALPHA",
        hud_value_left_center = "VÙNG AN TOÀN TRÁI", hud_value_right_center = "VÙNG AN TOÀN PHẢI",
        hud_value_keep = "GIỮ ĐẾN BÀI THỬ SAU", hud_value_hide = "ẨN KHI KẾT THÚC",
        hud_value_seconds = "{seconds} GIÂY", hud_manual_test = "Bài thử sát thương thủ công",
        hud_target_count = "{count} mục tiêu", hud_result_context = "{target} · {seconds}giây · {count} mục tiêu",
    },
    ["pl"] = {
        hud_settings_close = "ZAMKNIJ", hud_tab_settings = "USTAWIENIA", hud_tab_results = "BIEŻĄCY TEST",
        hud_no_results = "Nie zapisano jeszcze obrażeń. Zamknij F1 i pozwól Palowi zadać pierwszy cios.",
        hud_group_general = "OGÓLNE", hud_group_measurement = "POMIAR", hud_group_display = "MIERNIK WALKI",
        hud_group_output = "WYNIKI I WYJŚCIE", hud_group_test = "STEROWANIE TESTEM",
        hud_setting_measurement_mode = "Tryb sesji testowej", hud_setting_target_scope = "Dozwolone cele",
        hud_setting_final_duration = "Czas wyświetlania wyniku",
        hud_value_mode_manual = "RĘCZNE OKNO TESTU", hud_value_mode_target = "JEDEN TEST NA CEL",
        hud_value_scope_all = "WSZYSTKIE DZIKIE PALE", hud_value_scope_boss = "TYLKO BOSS / ALFA",
        hud_value_left_center = "BEZPIECZNA STREFA LEWA", hud_value_right_center = "BEZPIECZNA STREFA PRAWA",
        hud_value_keep = "DO NASTĘPNEGO TESTU", hud_value_hide = "UKRYJ PO ZAKOŃCZENIU",
        hud_value_seconds = "{seconds} S", hud_manual_test = "Ręczny test obrażeń",
        hud_target_count = "cele: {count}", hud_result_context = "{target} · {seconds}s · cele: {count}",
    },
}

function M.get(code, key)
    if key == "hud_skill_category_basic" then
        return M.skill_category_names[code] or M.skill_category_names.en
    end
    if key == "hud_skill_category_other" then
        return M.other_category_names[code] or M.other_category_names.en
    end
    local locale = M.strings[code] or M.strings.en
    local extra = M.extra_strings[code] or M.extra_strings.en
    return locale[key] or extra[key] or M.strings.en[key] or M.extra_strings.en[key]
end

function M.language_name(code)
    return M.native_names[code] or tostring(code or "")
end

return M
