param(
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) "Scripts\skill_names.lua")
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$languages = [ordered]@{
    "en" = "en"
    "zh-TW" = "tw"
    "zh-CN" = "cn"
    "ja" = "ja"
    "fr" = "fr"
    "it" = "it"
    "de" = "de"
    "es-ES" = "es"
    "pt-BR" = "pt"
    "ru" = "ru"
    "ko" = "ko"
    "id" = "id"
    "es-419" = "mx"
    "th" = "th"
    "tr" = "tr"
    "vi" = "vi"
    "pl" = "pl"
}

$anchorPattern = '<a\s+data-hover="\?s=Waza%2FEPalWazaID%3A%3A([^"]+)"\s+href="([^"]+)"[^>]*>(.*?)</a>'
$allNames = @{}
$coverage = [ordered]@{}

foreach ($entry in $languages.GetEnumerator()) {
    $code = $entry.Key
    $url = "https://paldb.cc/$($entry.Value)/Active_Skills"
    Write-Host "Downloading $code skill names from $url"
    $html = (Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 60).Content
    $matches = [regex]::Matches($html, $anchorPattern, [Text.RegularExpressions.RegexOptions]::Singleline)
    $seen = @{}
    foreach ($match in $matches) {
        $skillCode = [Uri]::UnescapeDataString($match.Groups[1].Value)
        $name = $match.Groups[3].Value -replace '<[^>]+>', ''
        $name = [Net.WebUtility]::HtmlDecode($name).Trim()
        if ($skillCode -eq "" -or $name -eq "") { continue }
        if ($seen.ContainsKey($skillCode) -and $seen[$skillCode] -ne $name) {
            throw "Conflicting $code names for $skillCode"
        }
        $seen[$skillCode] = $name
        if (-not $allNames.ContainsKey($skillCode)) { $allNames[$skillCode] = @{} }
        $allNames[$skillCode][$code] = $name
    }
    if ($seen.Count -lt 350) {
        throw "Unexpectedly low $code coverage: $($seen.Count) unique skills"
    }
    $coverage[$code] = $seen.Count
}

function ConvertTo-LuaString([string]$Value) {
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    $escaped = $escaped.Replace("`r", '\r').Replace("`n", '\n')
    return '"' + $escaped + '"'
}

$builder = [Text.StringBuilder]::new()
[void]$builder.AppendLine("-- Generated by tools/update_skill_names.ps1 from PalDB Active_Skills pages.")
[void]$builder.AppendLine("-- Source data reflects Palworld's localized game data; do not edit this table manually.")
[void]$builder.AppendLine("local M = {}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("local names = {")
foreach ($skillCode in ($allNames.Keys | Sort-Object)) {
    [void]$builder.AppendLine("    [$(ConvertTo-LuaString $skillCode)] = {")
    foreach ($languageCode in $languages.Keys) {
        $name = $allNames[$skillCode][$languageCode]
        if ($null -ne $name) {
            [void]$builder.AppendLine("        [$(ConvertTo-LuaString $languageCode)] = $(ConvertTo-LuaString $name),")
        }
    }
    [void]$builder.AppendLine("    },")
}
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("M.skill_count = $($allNames.Count)")
[void]$builder.AppendLine("M.coverage = {")
foreach ($languageCode in $languages.Keys) {
    [void]$builder.AppendLine("    [$(ConvertTo-LuaString $languageCode)] = $($coverage[$languageCode]),")
}
[void]$builder.AppendLine("}")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("function M.get(skill_code, language_code)")
[void]$builder.AppendLine('    local entry = names[tostring(skill_code or "")]')
[void]$builder.AppendLine("    if entry == nil then return nil end")
[void]$builder.AppendLine("    return entry[language_code] or entry.en")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine("")
[void]$builder.AppendLine("return M")

$parent = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $parent -Force | Out-Null
[IO.File]::WriteAllText($OutputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $($allNames.Count) skill codes to $OutputPath"
foreach ($entry in $coverage.GetEnumerator()) {
    Write-Host "  $($entry.Key): $($entry.Value)"
}
